apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/krakend.json",
             "version" : 3,
             "name" : "massil_test",
             "port" : 8082,
             "host" : [ "http://localhost:8022" ],
             "timeout" : "3000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "echo_endpoint" : false,
             "plugin" : {
               "pattern" : ".so",
               "folder" : "/opt/krakend/plugins/"
             },
             "endpoints" : [ {
               "endpoint" : "/auth/company",
               "backend" : [ {
                 "host" : [ "https://fake-json-api.mock.beeceptor.com" ],
                 "url_pattern" : "/companies",
                 "is_collection" : false,
                 "encoding" : "json",
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "consumer2" : "$2a$10$XNjbP6m0GgSTrk4p/.22buCqxjws/RQ3amtq375njKqto8IR//QW."
                   }
                 }
               },
               "output_encoding" : "json",
               "method" : "GET"
             }, {
               "endpoint" : "/auth/user",
               "backend" : [ {
                 "host" : [ "https://fake-json-api.mock.beeceptor.com" ],
                 "url_pattern" : "/users",
                 "is_collection" : false,
                 "encoding" : "json",
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "consumer2" : "$2a$10$XNjbP6m0GgSTrk4p/.22buCqxjws/RQ3amtq375njKqto8IR//QW."
                   }
                 }
               },
               "output_encoding" : "json",
               "method" : "GET"
             } ],
             "extra_config" : { }
           }
