apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/krakend.json",
             "version" : 3,
             "name" : "MassilGW",
             "port" : 8082,
             "host" : [ "localhost" ],
             "timeout" : "10000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "endpoints" : [ {
               "endpoint" : "/mucontext/getBrew",
               "backend" : [ {
                 "host" : [ "https://api.openbrewerydb.org" ],
                 "url_pattern" : "/breweries",
                 "is_collection" : true,
                 "encoding" : "json",
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "modifier/jmespath" : {
                   "expr" : "[?city == 'Oregon' ].name"
                 },
                 "proxy" : {
                   "static" : {
                     "data" : {
                       "status" : 200,
                       "message" : "success"
                     },
                     "strategy" : "always"
                   }
                 }
               },
               "output_encoding" : "json",
               "method" : "GET"
             }, {
               "endpoint" : "/testservices/sample",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/3",
                 "extra_config" : { },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "method" : "GET"
             }, {
               "endpoint" : "/testservices/enrolldetails",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects",
                 "is_collection" : true,
                 "encoding" : "json",
                 "extra_config" : {
                   "plugin/req-resp-modifier" : {
                     "name" : [ "content-replacer" ],
                     "content-replacer" : {
                       "da" : {
                         "find" : "enrollCustomer",
                         "replace" : "collection[*].data | [0].capacity",
                         "regexp" : false
                       }
                     }
                   },
                   "proxy" : {
                     "flatmap_filter" : [ {
                       "type" : "append",
                       "args" : [ "collection.*.data", "enrollData.*.name" ]
                     } ]
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "output_encoding" : "json",
               "method" : "GET",
               "input_query_strings" : [ "id" ],
               "cache_ttl" : "1m",
               "timeout" : "10s"
             }, {
               "endpoint" : "/testservices/tickets",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects",
                 "is_collection" : false,
                 "encoding" : "json",
                 "method" : "GET"
               } ],
               "extra_config" : { },
               "output_encoding" : "json",
               "method" : "GET"
             } ],
             "extra_config" : {
               "security/cors" : {
                 "allow_origins" : [ "*" ],
                 "allow_methods" : [ "GET", "HEAD", "POST" ],
                 "allow_headers" : [ "*" ],
                 "allow_credentials" : true
               }
             }
           }
