apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/v2.7/krakend.json",
             "version" : 3,
             "name" : "gateway",
             "port" : 8082,
             "timeout" : "3000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "echo_endpoint" : true,
             "plugin" : {
               "pattern" : ".so",
               "folder" : "/opt/krakend/plugins/"
             },
             "endpoints" : [ {
               "endpoint" : "/sampleflatmap/flatmapep",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects",
                 "is_collection" : true,
                 "extra_config" : {
                   "proxy" : {
                     "flatmap_filter" : [ {
                       "type" : "move",
                       "args" : [ "collection.*.data", "collection.*.Address" ]
                     }, {
                       "type" : "move",
                       "args" : [ "collection.*.Address.color", "collection.*.Address.customcolor" ]
                     } ]
                   }
                 },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/api-keys" : {
                   "roles" : [ "finance" ]
                 }
               },
               "method" : "GET"
             } ],
             "extra_config" : {
               "router" : {
                 "return_error_msg" : true
               },
               "security/cors" : {
                 "allow_origins" : [ "*" ],
                 "allow_methods" : [ "GET", "HEAD", "POST" ],
                 "allow_headers" : [ "*" ],
                 "expose_headers" : [ "*" ],
                 "allow_credentials" : true
               },
               "auth/api-keys" : {
                 "identifier" : "Authorization",
                 "strategy" : "header",
                 "keys" : [ {
                   "key" : "f38a07f1-c045-4872-8c5d-6f96638c0c60",
                   "roles" : [ "finance" ]
                 } ]
               },
               "telemetry/logging" : {
                 "format" : "default",
                 "syslog_facility" : "local3",
                 "level" : "DEBUG",
                 "prefix" : "MASSIL",
                 "stdout" : true
               },
               "telemetry/logstash" : {
                 "enabled" : true
               }
             }
           }
