apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {

             "$schema" : "https://www.krakend.io/schema/krakend.json",

             "version" : 3,

             "name" : "gitgateway",

             "port" : 8082,

             "timeout" : "3000ms",

             "cache_ttl" : "300s",

             "debug_endpoint" : false,

             "echo_endpoint" : false,

             "endpoints" : [ {

               "endpoint" : "/keyclockProtected2",

               "backend" : [ {

                 "host" : [ "http://localhost:8082" ],

                 "url_pattern" : "/__health"

               } ],

               "extra_config" : {

                 "auth/validator" : {

                   "alg" : "RS256",

                   "jwk_url" : "http://10.175.1.57:8080/realms/master/protocol/openid-connect/certs",

                   "issuer" : "http://10.175.1.57:8080/realms/master",

                   "disable_jwk_security" : true,

                   "scopes_matcher" : "any",

                   "scopes" : [ "democlient1" ],

                   "scopes_key" : "scope"

                 }

               }

             } ],

             "extra_config" : { }

           }
