apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/v2.7/krakend.json",
             "version" : 3,
             "name" : "gateway",
             "port" : 8082,
             "timeout" : "6000ms",
             "cache_ttl" : "1h",
             "debug_endpoint" : false,
             "echo_endpoint" : true,
             "plugin" : {
               "pattern" : ".so",
               "folder" : "/opt/krakend/plugins/"
             },
             "endpoints" : [ {
               "method" : "GET",
               "backend" : [ {
                 "method" : "GET",
                 "url_pattern" : "/posts/{id}",
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "is_collection" : false,
                 "extra_config" : { }
               } ],
               "endpoint" : "/swift/requestpolicy/{id}",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "newClient" ],
                   "scopes_key" : "scope"
                 },
                 "security/policies" : {
                   "req" : {
                     "policies" : [ "req_params.Id.matches('^[0-9]+$')" ],
                     "error" : {
                       "body" : "{\"ErrorMessage\":\"Please provide integers only\"}",
                       "status" : 400,
                       "content_type" : "application/json"
                     }
                   }
                 }
               }
             }, {
               "method" : "POST",
               "output_encoding" : "json",
               "backend" : [ {
                 "method" : "POST",
                 "url_pattern" : "/services/TemperatureConversions.wso",
                 "host" : [ "http://webservices.daehosting.com" ],
                 "encoding" : "xml",
                 "extra_config" : {
                   "backend/soap" : {
                     "template" : "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+Cjxzb2FwZW52OkVudmVsb3BlIHhtbG5zOnNvYXBlbnY9Imh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3NvYXAvZW52ZWxvcGUvIj4KICAgIDxzb2FwZW52OkhlYWRlci8+CiAgICA8c29hcGVudjpCb2R5PgogICAgICAgIDx3ZWI6RmFocmVuaGVpdFRvQ2Vsc2l1cyB4bWxuczp3ZWI9Imh0dHA6Ly93ZWJzZXJ2aWNlcy5kYWVob3N0aW5nLmNvbS90ZW1wZXJhdHVyZSI+CiAgICAgICAgICAgIDx3ZWI6bkZhaHJlbmhlaXQ+e3sucmVxX2JvZHkuRmFocmVuaGVpdFRvQ2Vsc2l1cy5uRmFocmVuaGVpdH19PC93ZWI6bkZhaHJlbmhlaXQ+CiAgICAgICAgPC93ZWI6RmFocmVuaGVpdFRvQ2Vsc2l1cz4KICAgIDwvc29hcGVudjpCb2R5Pgo8L3NvYXBlbnY6RW52ZWxvcGU+Cg==",
                     "content_type" : "text/xml"
                   }
                 },
                 "sd" : "static"
               } ],
               "endpoint" : "/soaptorest/fahrenheitToCelsius",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakendtest" ],
                   "scopes_key" : "scope"
                 },
                 "modifier/response-body-generator" : {
                   "template" : "e3t0b0pzb24gLnJlc3BfYm9keS5FbnZlbG9wZS5Cb2R5fX0="
                 }
               }
             }, {
               "method" : "POST",
               "output_encoding" : "json",
               "backend" : [ {
                 "method" : "POST",
                 "url_pattern" : "/services/TemperatureConversions.wso",
                 "host" : [ "http://webservices.daehosting.com" ],
                 "encoding" : "xml",
                 "extra_config" : {
                   "backend/soap" : {
                     "template" : "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+Cjxzb2FwZW52OkVudmVsb3BlIHhtbG5zOnNvYXBlbnY9Imh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3NvYXAvZW52ZWxvcGUvIj4KICAgIDxzb2FwZW52OkhlYWRlci8+CiAgICA8c29hcGVudjpCb2R5PgogICAgICAgIDx3ZWI6V2luZENoaWxsSW5DZWxzaXVzIHhtbG5zOndlYj0iaHR0cDovL3dlYnNlcnZpY2VzLmRhZWhvc3RpbmcuY29tL3RlbXBlcmF0dXJlIj4KICAgICAgICAgICAgPHdlYjpuQ2Vsc2l1cz57ey5yZXFfYm9keS5XaW5kQ2hpbGxJbkNlbHNpdXMubkNlbHNpdXN9fTwvd2ViOm5DZWxzaXVzPgogICAgICAgICAgICA8d2ViOm5XaW5kU3BlZWQ+e3sucmVxX2JvZHkuV2luZENoaWxsSW5DZWxzaXVzLm5XaW5kU3BlZWR9fTwvd2ViOm5XaW5kU3BlZWQ+CiAgICAgICAgPC93ZWI6V2luZENoaWxsSW5DZWxzaXVzPgogICAgPC9zb2FwZW52OkJvZHk+Cjwvc29hcGVudjpFbnZlbG9wZT4K",
                     "content_type" : "text/xml"
                   }
                 },
                 "sd" : "static"
               } ],
               "endpoint" : "/soaptorest/windChillInCelsius",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakendtest" ],
                   "scopes_key" : "scope"
                 },
                 "modifier/response-body-generator" : {
                   "template" : "e3t0b0pzb24gLnJlc3BfYm9keS5FbnZlbG9wZS5Cb2R5fX0="
                 }
               }
             }, {
               "method" : "POST",
               "output_encoding" : "json",
               "backend" : [ {
                 "method" : "POST",
                 "url_pattern" : "/services/TemperatureConversions.wso",
                 "host" : [ "http://webservices.daehosting.com" ],
                 "encoding" : "xml",
                 "extra_config" : {
                   "backend/soap" : {
                     "template" : "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+Cjxzb2FwZW52OkVudmVsb3BlIHhtbG5zOnNvYXBlbnY9Imh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3NvYXAvZW52ZWxvcGUvIj4KICAgIDxzb2FwZW52OkhlYWRlci8+CiAgICA8c29hcGVudjpCb2R5PgogICAgICAgIDx3ZWI6V2luZENoaWxsSW5GYWhyZW5oZWl0IHhtbG5zOndlYj0iaHR0cDovL3dlYnNlcnZpY2VzLmRhZWhvc3RpbmcuY29tL3RlbXBlcmF0dXJlIj4KICAgICAgICAgICAgPHdlYjpuRmFocmVuaGVpdD57ey5yZXFfYm9keS5XaW5kQ2hpbGxJbkZhaHJlbmhlaXQubkZhaHJlbmhlaXR9fTwvd2ViOm5GYWhyZW5oZWl0PgogICAgICAgICAgICA8d2ViOm5XaW5kU3BlZWQ+e3sucmVxX2JvZHkuV2luZENoaWxsSW5GYWhyZW5oZWl0Lm5XaW5kU3BlZWR9fTwvd2ViOm5XaW5kU3BlZWQ+CiAgICAgICAgPC93ZWI6V2luZENoaWxsSW5GYWhyZW5oZWl0PgogICAgPC9zb2FwZW52OkJvZHk+Cjwvc29hcGVudjpFbnZlbG9wZT4K",
                     "content_type" : "text/xml"
                   }
                 },
                 "sd" : "static"
               } ],
               "endpoint" : "/soaptorest/windChillInFahrenheit",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakendtest" ],
                   "scopes_key" : "scope"
                 },
                 "modifier/response-body-generator" : {
                   "template" : "e3t0b0pzb24gLnJlc3BfYm9keS5FbnZlbG9wZS5Cb2R5fX0="
                 }
               }
             }, {
               "method" : "POST",
               "output_encoding" : "json",
               "backend" : [ {
                 "method" : "POST",
                 "url_pattern" : "/services/TemperatureConversions.wso",
                 "host" : [ "http://webservices.daehosting.com" ],
                 "encoding" : "xml",
                 "extra_config" : {
                   "backend/soap" : {
                     "template" : "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+Cjxzb2FwZW52OkVudmVsb3BlIHhtbG5zOnNvYXBlbnY9Imh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3NvYXAvZW52ZWxvcGUvIj4KICAgIDxzb2FwZW52OkhlYWRlci8+CiAgICA8c29hcGVudjpCb2R5PgogICAgICAgIDx3ZWI6Q2Vsc2l1c1RvRmFocmVuaGVpdCB4bWxuczp3ZWI9Imh0dHA6Ly93ZWJzZXJ2aWNlcy5kYWVob3N0aW5nLmNvbS90ZW1wZXJhdHVyZSI+CiAgICAgICAgICAgIDx3ZWI6bkNlbHNpdXM+e3sucmVxX2JvZHkuQ2Vsc2l1c1RvRmFocmVuaGVpdC5uQ2Vsc2l1c319PC93ZWI6bkNlbHNpdXM+CiAgICAgICAgPC93ZWI6Q2Vsc2l1c1RvRmFocmVuaGVpdD4KICAgIDwvc29hcGVudjpCb2R5Pgo8L3NvYXBlbnY6RW52ZWxvcGU+Cg==",
                     "content_type" : "text/xml"
                   }
                 },
                 "sd" : "static"
               } ],
               "endpoint" : "/soaptorest/celsiusToFahrenheit",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakendtest" ],
                   "scopes_key" : "scope"
                 },
                 "modifier/response-body-generator" : {
                   "template" : "e3t0b0pzb24gLnJlc3BfYm9keS5FbnZlbG9wZS5Cb2R5fX0="
                 }
               }
             }, {
               "method" : "POST",
               "output_encoding" : "no-op",
               "backend" : [ {
                 "method" : "POST",
                 "url_pattern" : "/calculator.asmx",
                 "host" : [ "http://www.dneonline.com" ],
                 "extra_config" : { }
               } ],
               "endpoint" : "/soappassthrough/",
               "extra_config" : { }
             } ],
             "extra_config" : {
               "router" : {
                 "return_error_msg" : true
               },
               "security/cors" : {
                 "allow_origins" : [ "*" ],
                 "allow_methods" : [ "GET", "POST", "PUT", "DELETE", "PATCH" ],
                 "allow_headers" : [ "*" ],
                 "expose_headers" : [ "*" ],
                 "allow_credentials" : true
               },
               "plugin/http-server" : {
                 "name" : [ "url-rewrite" ],
                 "ip-filter" : {
                   "id" : 1,
                   "CIDR" : [ "10.175.1.70" ],
                   "allow" : false
                 }
               }
             }
           }
