apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/v2.7/krakend.json",
             "version" : 3,
             "name" : "gateway",
             "port" : 8082,
             "timeout" : "6000ms",
             "cache_ttl" : "1h",
             "debug_endpoint" : false,
             "echo_endpoint" : true,
             "plugin" : {
               "pattern" : ".so",
               "folder" : "/opt/krakend/plugins/"
             },
             "endpoints" : [ {
               "method" : "POST",
               "output_encoding" : "no-op",
               "backend" : [ {
                 "method" : "POST",
                 "url_pattern" : "/calculator.asmx",
                 "host" : [ "http://www.dneonline.com" ],
                 "extra_config" : { }
               } ],
               "endpoint" : "/soappassthrough/",
               "extra_config" : { }
             } ],
             "extra_config" : {
               "router" : {
                 "return_error_msg" : true
               },
               "security/cors" : {
                 "allow_origins" : [ "*" ],
                 "allow_methods" : [ "GET", "POST", "PUT", "DELETE", "PATCH" ],
                 "allow_headers" : [ "*" ],
                 "expose_headers" : [ "*" ],
                 "allow_credentials" : true
               },
               "plugin/http-server" : {
                 "name" : [ "url-rewrite" ],
                 "ip-filter" : {
                   "id" : 1,
                   "CIDR" : [ "10.175.1.70" ],
                   "allow" : false
                 }
               },
               "auth/api-keys" : {
                 "identifier" : "Authorization",
                 "strategy" : "header",
                 "keys" : [ {
                   "key" : "819462f2-d873-4115-bfc0-891d32398365"
                 } ]
               }
             }
           }
