apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/krakend.json",
             "version" : 3,
             "name" : "Test sample Gateway10",
             "port" : 8082,
             "host" : [ "http://localhost" ],
             "timeout" : "3000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "echo_endpoint" : false,
             "plugin" : {
               "pattern" : ".so",
               "folder" : "/opt/krakend/plugins/"
             },
             "endpoints" : [ {
               "endpoint" : "/contex7/keyy",
               "backend" : [ {
                 "host" : [ "http://localhost.com" ],
                 "url_pattern" : "/posts",
                 "is_collection" : false,
                 "encoding" : "json",
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://localhost:8080/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://localhost:8080/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "json",
               "method" : "POST"
             }, {
               "endpoint" : "/contex7/keysf",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts",
                 "is_collection" : false,
                 "encoding" : "json",
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://localhost:8080/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://localhost:8080/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "json",
               "method" : "GET"
             }, {
               "endpoint" : "/contex7/keyss",
               "backend" : [ {
                 "host" : [ "http://localhost.com" ],
                 "url_pattern" : "/posts",
                 "is_collection" : false,
                 "encoding" : "json",
                 "extra_config" : { },
                 "method" : "POST"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://localhost:8080/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://localhost:8080/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "json-collection",
               "method" : "GET"
             }, {
               "endpoint" : "/contex7/key",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts",
                 "is_collection" : true,
                 "encoding" : "json",
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://localhost:8080/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://localhost:8080/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "json",
               "method" : "GET"
             }, {
               "endpoint" : "/contex7/samp",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts",
                 "is_collection" : false,
                 "encoding" : "xml",
                 "extra_config" : { },
                 "method" : "POST"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://localhost:8080/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://localhost:8080/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "json",
               "method" : "PATCH"
             }, {
               "endpoint" : "/contex7/keys10",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts",
                 "is_collection" : true,
                 "encoding" : "xml",
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://localhost:8080/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://localhost:8080/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "json",
               "method" : "DELETE"
             }, {
               "endpoint" : "/contex7/keys9",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts",
                 "is_collection" : false,
                 "encoding" : "json",
                 "extra_config" : { },
                 "method" : "POST"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://localhost:8080/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://localhost:8080/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "json",
               "method" : "PUT"
             }, {
               "endpoint" : "/contex7/keys8",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/users",
                 "is_collection" : false,
                 "encoding" : "json",
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://localhost:8080/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://localhost:8080/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "json-collection",
               "method" : "GET"
             }, {
               "endpoint" : "/contex7/keys7",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts",
                 "is_collection" : true,
                 "encoding" : "json",
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://localhost:8080/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://localhost:8080/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "json",
               "method" : "POST"
             }, {
               "endpoint" : "/test3/testing",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts",
                 "is_collection" : true,
                 "encoding" : "json",
                 "method" : "GET"
               } ],
               "extra_config" : { },
               "output_encoding" : "json",
               "method" : "GET"
             } ],
             "extra_config" : {
               "security/cors" : {
                 "allow_origins" : [ "tyy", "de" ],
                 "allow_methods" : [ "OPTIONS", "TRACE" ],
                 "allow_headers" : [ "dee", "a" ],
                 "expose_headers" : [ "tu", "abcd" ],
                 "max_age" : "15ms",
                 "allow_credentials" : true
               },
               "security/bot-detector" : {
                 "allow" : [ "abcd" ],
                 "cache_size" : 12,
                 "deny" : [ "deny" ],
                 "empty_user_agent_is_bot" : true,
                 "patterns" : [ "ee" ]
               },
               "security/http" : {
                 "allowed_hosts" : [ "host" ],
                 "allowed_hosts_are_regex" : false,
                 "browser_xss_filter" : true,
                 "content_security_policy" : "degault",
                 "content_type_nosniff" : true,
                 "custom_frame_options_value" : "x-frame",
                 "force_sts_header" : false,
                 "frame_deny" : true,
                 "hpkp_public_key" : "pin",
                 "is_development" : false,
                 "referrer_policy" : "same-origin",
                 "ssl_host" : "domain",
                 "ssl_proxy_headers" : {
                   "proxy" : "https",
                   "ddedj" : "httpss"
                 },
                 "ssl_redirect" : true,
                 "sts_include_subdomains" : true,
                 "sts_seconds" : 12
               },
               "plugin/http-server" : {
                 "name" : [ "jwk-aggregator" ],
                 "ip-filter" : {
                   "id" : 1,
                   "CIDR" : [ "local.com" ],
                   "allow" : true,
                   "client_ip_headers" : [ "test.com" ],
                   "trusted_proxies" : [ "example.com", "ping.com" ]
                 },
                 "jwk-aggregator" : {
                   "id" : 1,
                   "cache" : true,
                   "origins" : [ "ee" ],
                   "port" : 2345
                 }
               },
               "telemetry/moesif" : {
                 "application_id" : "23",
                 "user_id_headers" : [ "fdf" ],
                 "user_id_jwt_claim" : "45",
                 "debug" : true
               }
             }
           }
