apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/v2.7/krakend.json",
             "version" : 3,
             "name" : "gateway",
             "port" : 8082,
             "timeout" : "3000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "echo_endpoint" : true,
             "plugin" : {
               "pattern" : ".so",
               "folder" : "/opt/krakend/plugins/"
             },
             "endpoints" : [ {
               "endpoint" : "/rest/tosoapquery",
               "backend" : [ {
                 "host" : [ "http://www.dneonline.com" ],
                 "url_pattern" : "/calculator.asmx",
                 "is_collection" : false,
                 "encoding" : "xml",
                 "extra_config" : {
                   "modifier/body-generator" : {
                     "content_type" : "text/xml",
                     "debug" : true,
                     "template" : "PHNvYXBlbnY6RW52ZWxvcGUgeG1sbnM6c29hcGVudj0iaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvc29hcC9lbnZlbG9wZS8iIHhtbG5zOnRlbT0iaHR0cDovL3RlbXB1cmkub3JnLyI+CiAgIDxzb2FwZW52OkhlYWRlci8+CiAgIDxzb2FwZW52OkJvZHk+CiAgICAgIDx0ZW06QWRkPgogICAgICAgICA8dGVtOmludEE+e3sgLnJlcV9xdWVyeXN0cmluZy5hWzBdIH19PC90ZW06aW50QT4KICAgICAgICAgPHRlbTppbnRCPnt7IC5yZXFfcXVlcnlzdHJpbmcuYlswXSB9fTwvdGVtOmludEI+CiAgICAgIDwvdGVtOkFkZD4KICAgPC9zb2FwZW52OkJvZHk+Cjwvc29hcGVudjpFbnZlbG9wZT4="
                   }
                 },
                 "method" : "POST",
                 "sd" : "static"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakendtest" ],
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "xml",
               "method" : "POST",
               "input_query_strings" : [ "a", "b" ]
             }, {
               "endpoint" : "/rest/tosoapheader",
               "backend" : [ {
                 "host" : [ "http://www.dneonline.com" ],
                 "url_pattern" : "/calculator.asmx",
                 "is_collection" : false,
                 "encoding" : "xml",
                 "extra_config" : {
                   "modifier/body-generator" : {
                     "content_type" : "text/xml",
                     "debug" : true,
                     "template" : "PHNvYXBlbnY6RW52ZWxvcGUgeG1sbnM6c29hcGVudj0iaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvc29hcC9lbnZlbG9wZS8iIHhtbG5zOnRlbT0iaHR0cDovL3RlbXB1cmkub3JnLyI+CiAgIDxzb2FwZW52OkhlYWRlci8+CiAgIDxzb2FwZW52OkJvZHk+CiAgICAgIDx0ZW06QWRkPgogICAgICAgICA8dGVtOmludEE+e3sgLnJlcV9oZWFkZXJzLmEgfX08L3RlbTppbnRBPgogICAgICAgICA8dGVtOmludEI+e3sgLnJlcV9oZWFkZXJzLmIgfX08L3RlbTppbnRCPgogICAgICA8L3RlbTpBZGQ+CiAgIDwvc29hcGVudjpCb2R5Pgo8L3NvYXBlbnY6RW52ZWxvcGU+"
                   }
                 },
                 "method" : "POST",
                 "sd" : "static"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakendtest" ],
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "xml",
               "input_headers" : [ "a", "b" ],
               "method" : "POST"
             }, {
               "endpoint" : "/rest/tosoap",
               "backend" : [ {
                 "host" : [ "http://www.dneonline.com" ],
                 "url_pattern" : "/calculator.asmx",
                 "is_collection" : false,
                 "encoding" : "xml",
                 "extra_config" : {
                   "modifier/body-generator" : {
                     "content_type" : "text/xml",
                     "debug" : true,
                     "template" : "PHNvYXBlbnY6RW52ZWxvcGUgeG1sbnM6c29hcGVudj0iaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvc29hcC9lbnZlbG9wZS8iIHhtbG5zOnRlbT0iaHR0cDovL3RlbXB1cmkub3JnLyI+CiAgIDxzb2FwZW52OkhlYWRlci8+CiAgIDxzb2FwZW52OkJvZHk+CiAgICAgIDx0ZW06QWRkPgogICAgICAgICA8dGVtOmludEE+e3sgLnJlcV9ib2R5LmEgfX08L3RlbTppbnRBPgogICAgICAgICA8dGVtOmludEI+e3sgLnJlcV9ib2R5LmIgfX08L3RlbTppbnRCPgogICAgICA8L3RlbTpBZGQ+CiAgIDwvc29hcGVudjpCb2R5Pgo8L3NvYXBlbnY6RW52ZWxvcGU+"
                   }
                 },
                 "method" : "POST",
                 "sd" : "static"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakendtest" ],
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "xml",
               "method" : "POST"
             }, {
               "endpoint" : "/martianapi/bmartianep",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/1",
                 "extra_config" : {
                   "modifier/martian" : {
                     "body.Modifier" : {
                       "scope" : [ "response" ],
                       "@comment" : "Send a {'msg':'you rock!'}",
                       "body" : "eyJtc2ciOiJ5b3Ugcm9jayEifQ==",
                       "contentType" : "application/json"
                     }
                   }
                 },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakendtest" ],
                   "scopes_key" : "scope"
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/martianapi/martianep",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/1",
                 "is_collection" : false,
                 "extra_config" : {
                   "qos/ratelimit/proxy" : {
                     "every" : "1m",
                     "max_rate" : 5,
                     "capacity" : 5
                   },
                   "modifier/martian" : {
                     "body.Modifier" : {
                       "scope" : [ "response" ],
                       "@comment" : "Send a {'msg':'you rock!'}",
                       "body" : "eyJtc2ciOiJ5b3Ugcm9jayEifQ==",
                       "contentType" : "application/json"
                     }
                   }
                 },
                 "method" : "GET",
                 "sd" : "static"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakendtest" ],
                   "scopes_key" : "scope"
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/jmes/respmanupilation",
               "backend" : [ {
                 "host" : [ "https://api.nationalize.io" ],
                 "url_pattern" : "/",
                 "extra_config" : {
                   "modifier/jmespath" : {
                     "expr" : "country[?probability > `0.03` ].country_id"
                   }
                 },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakendtest" ],
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "json",
               "method" : "GET",
               "input_query_strings" : [ "name" ]
             } ],
             "extra_config" : {
               "router" : {
                 "return_error_msg" : true
               },
               "security/cors" : {
                 "allow_origins" : [ "*" ],
                 "allow_methods" : [ "GET", "HEAD", "POST" ],
                 "allow_headers" : [ "*" ],
                 "expose_headers" : [ "*" ],
                 "allow_credentials" : true
               }
             }
           }
