apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/krakend.json",
             "version" : 3,
             "name" : "MassilGW",
             "port" : 8082,
             "host" : [ "localhost" ],
             "timeout" : "3000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "echo_endpoint" : false,
             "endpoints" : [ {
               "endpoint" : "/basicoperation/testquery",
               "backend" : [ {
                 "host" : [ "https://api.nationalize.io" ],
                 "url_pattern" : "/",
                 "is_collection" : false,
                 "method" : "GET"
               } ],
               "extra_config" : { },
               "method" : "GET",
               "input_query_strings" : [ "name" ]
             }, {
               "endpoint" : "/basicoperation/merge",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/1",
                 "is_collection" : false,
                 "method" : "GET"
               }, {
                 "host" : [ "https://api.nationalize.io" ],
                 "url_pattern" : "/",
                 "extra_config" : { },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "method" : "GET",
               "input_query_strings" : [ "name" ]
             }, {
               "endpoint" : "/basicoperation/flatmap",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev/" ],
                 "url_pattern" : "/objects",
                 "is_collection" : true,
                 "extra_config" : {
                   "proxy" : {
                     "flatmap_filter" : [ {
                       "type" : "move",
                       "args" : [ "collection.*.data", "collection.*.newdata" ]
                     } ]
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "method" : "GET"
             }, {
               "endpoint" : "/basicoperation/flatmapobject",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects/7",
                 "extra_config" : {
                   "proxy" : {
                     "flatmap_filter" : [ {
                       "type" : "move",
                       "args" : [ "data.year", "YEAR" ]
                     } ]
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "method" : "GET"
             }, {
               "endpoint" : "/basicoperation/jmes",
               "backend" : [ {
                 "host" : [ "https://api.nationalize.io/" ],
                 "url_pattern" : "/",
                 "extra_config" : {
                   "modifier/jmespath" : {
                     "expr" : "country[?probability > `0.0` ].country_id"
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "method" : "GET",
               "input_query_strings" : [ "name" ]
             } ],
             "extra_config" : { }
           }
