apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/krakend.json",
             "version" : 3,
             "name" : "gitgateway",
             "port" : 8082,
             "timeout" : "3000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "echo_endpoint" : false,
             "endpoints" : [ {
               "endpoint" : "/demo2345/keycloak-protected2",
               "backend" : [ {
                 "host" : [ "http://localhost:8082" ],
                 "url_pattern" : "/__health",
                 "extra_config" : {
                   "proxy" : {
                     "shadow" : true
                   }
                 }
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "consumer_ramesh" : "$2a$10$zptiG1eswxpKw9.OHVKjx.qKyShcbuGSWGetaMIRQ/vazBIgiiOP2",
                     "consumer_neel" : "$2a$10$eHerowcCmAhwo0sRgvtp.uDVmRzqUvT3Hkr9v5aZRmkMMUgat.6j."
                   }
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/demo2345/keycloak-protected1",
               "backend" : [ {
                 "host" : [ "http://localhost:8082" ],
                 "url_pattern" : "/__health"
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "consumer_ramesh" : "$2a$10$zptiG1eswxpKw9.OHVKjx.qKyShcbuGSWGetaMIRQ/vazBIgiiOP2",
                     "consumer_neel" : "$2a$10$eHerowcCmAhwo0sRgvtp.uDVmRzqUvT3Hkr9v5aZRmkMMUgat.6j."
                   }
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/api2/keycloak-protected1",
               "backend" : [ {
                 "host" : [ "http://localhost:8082" ],
                 "url_pattern" : "/__health"
               } ],
               "extra_config" : {
                 "auth/api-keys" : {
                   "roles" : [ "consumer_ramesh" ]
                 }
               },
               "method" : "GET"
             } ],
             "extra_config" : {
               "auth/api-keys" : {
                 "strategy" : "header",
                 "identifier" : "Authorization",
                 "keys" : [ {
                   "key" : "2609d1c3-941a-481e-91b6-f7d1d4eaa422",
                   "roles" : [ "consumer_ramesh" ],
                   "@description" : "b to c app"
                 } ]
               },
               "security/cors" : {
                 "allow_origins" : [ "*" ],
                 "allow_methods" : [ "GET", "HEAD", "POST", "PUT", "DELETE" ],
                 "allow_headers" : [ "*" ],
                 "expose_headers" : [ "Content-Length", "Content-Type" ],
                 "max_age" : "12h",
                 "allow_credentials" : true
               }
             }
           }
