apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
  namespace: krakendDemo-namespace
data:
  krakend.json: |
    {
      "$schema" : "https://www.krakend.io/schema/krakend.json",
      "version" : 3,
      "name" : "gitgateway",
      "port" : 8080,
      "timeout" : "3000ms",
      "cache_ttl" : "300s",
      "debug_endpoint" : false,
      "echo_endpoint" : false,
      "endpoints" : [ {
        "endpoint" : "/keycloak-protected1",
        "backend" : [ {
          "host" : [ "http://localhost:8080" ],
          "url_pattern" : "/__health"
        } ],
        "extra_config" : { }
      } ],
      "extra_config" : { }
    }

