apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/krakend.json",
             "version" : 3,
             "name" : "MassilGW",
             "port" : 8082,
             "host" : [ "localhost" ],
             "timeout" : "3000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "echo_endpoint" : false,
             "endpoints" : [ {
               "endpoint" : "/basictest/flatmap",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects",
                 "is_collection" : true,
                 "extra_config" : {
                   "proxy" : {
                     "flatmap_filter" : [ {
                       "type" : "move",
                       "args" : [ "collection.*.data", "collection.*.newdata" ]
                     } ]
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "sparrow" : "$2a$10$fy77r/0CaL7W987u23TAyeSwNeinqvCj0LXKKfvO60tw0wdNcS2IO"
                   }
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/basictest/flatmapobject",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects/7",
                 "extra_config" : {
                   "proxy" : {
                     "flatmap_filter" : [ {
                       "type" : "move",
                       "args" : [ "data.year", "Year" ]
                     } ]
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "sparrow" : "$2a$10$fy77r/0CaL7W987u23TAyeSwNeinqvCj0LXKKfvO60tw0wdNcS2IO"
                   }
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/basictest/deny",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/1",
                 "is_collection" : false,
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "sparrow" : "$2a$10$fy77r/0CaL7W987u23TAyeSwNeinqvCj0LXKKfvO60tw0wdNcS2IO"
                   }
                 }
               },
               "method" : "GET"
             } ],
             "extra_config" : { }
           }
