apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/krakend.json",
             "version" : 3,
             "name" : "MassilGW",
             "port" : 8082,
             "host" : [ "localhost" ],
             "timeout" : "10000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "endpoints" : [ {
               "endpoint" : "/tickets/stopticket",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects/8",
                 "encoding" : "json",
                 "extra_config" : {
                   "proxy" : {
                     "flatmap_filter" : [ {
                       "type" : "move",
                       "args" : [ "collection.*.data", "collection.*.newdata" ]
                     }, {
                       "type" : "move",
                       "args" : [ "collection.*.data", "collection.*.newdata" ]
                     } ]
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "output_encoding" : "json-collection",
               "method" : "GET"
             }, {
               "endpoint" : "/tickets/backendrespmanipulation",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects",
                 "is_collection" : true,
                 "encoding" : "json",
                 "method" : "GET"
               } ],
               "extra_config" : { },
               "output_encoding" : "json",
               "method" : "GET"
             } ],
             "extra_config" : {
               "security/cors" : {
                 "allow_origins" : [ "*" ],
                 "allow_methods" : [ "GET", "HEAD", "POST" ],
                 "allow_headers" : [ "*" ],
                 "allow_credentials" : true
               }
             }
           }
