apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/krakend.json",
             "version" : 3,
             "name" : "MassilGW",
             "port" : 8082,
             "host" : [ "localhost" ],
             "timeout" : "3000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "echo_endpoint" : false,
             "endpoints" : [ {
               "endpoint" : "/test/testEP",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/1",
                 "is_collection" : false,
                 "method" : "GET"
               } ],
               "extra_config" : { },
               "method" : "GET"
             }, {
               "endpoint" : "/test/soapservice",
               "backend" : [ {
                 "host" : [ "http://www.dneonline.com" ],
                 "url_pattern" : "/calculator.asmx",
                 "is_collection" : false,
                 "method" : "POST"
               } ],
               "extra_config" : { },
               "method" : "POST"
             }, {
               "endpoint" : "/test/testsoapep",
               "backend" : [ {
                 "host" : [ "http://www.dneonline.com" ],
                 "url_pattern" : "/calculator.asmx",
                 "is_collection" : false,
                 "method" : "GET"
               } ],
               "extra_config" : { },
               "output_encoding" : "no-op",
               "method" : "POST"
             } ],
             "extra_config" : { }
           }
