apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/v2.7/krakend.json",
             "version" : 3,
             "name" : "gateway",
             "port" : 8082,
             "timeout" : "6000ms",
             "cache_ttl" : "1h",
             "debug_endpoint" : false,
             "echo_endpoint" : true,
             "plugin" : {
               "pattern" : ".so",
               "folder" : "/opt/krakend/plugins/"
             },
             "endpoints" : [ {
               "endpoint" : "/v6/backend/objects",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects/8",
                 "is_collection" : false,
                 "encoding" : "json",
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakendtest" ],
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "json",
               "method" : "GET"
             }, {
               "endpoint" : "/v6/backend/object",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects/6",
                 "is_collection" : false,
                 "encoding" : "json",
                 "extra_config" : { },
                 "method" : "GET"
               }, {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/template",
                 "is_collection" : false,
                 "encoding" : "json",
                 "extra_config" : { },
                 "method" : "GET",
                 "sd" : "static"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakendtest" ],
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "json",
               "method" : "GET"
             }, {
               "endpoint" : "/endpointlevel/invalidrsppolicy",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/1",
                 "is_collection" : false,
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "newClient" ],
                   "scopes_key" : "scope"
                 },
                 "security/policies" : {
                   "resp" : {
                     "error" : {
                       "body" : "{\"Message\":\"Test feild is not present in response\"}",
                       "status" : 400,
                       "content_type" : "application/json"
                     },
                     "policies" : [ "!isEmpty(resp_data.test)" ]
                   }
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/endpointlevel/eresppolicy",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/1",
                 "is_collection" : false,
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "newClient" ],
                   "scopes_key" : "scope"
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/endpointlevel/erequestpolicy/{id}",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/{id}",
                 "is_collection" : false,
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "newClient" ],
                   "scopes_key" : "scope"
                 },
                 "security/policies" : {
                   "req" : {
                     "policies" : [ "req_params.Id.matches('^[0-9]+$')" ],
                     "error" : {
                       "body" : "{\"Message\":\"Please provide integer values only\"}",
                       "status" : 400,
                       "content_type" : "application/json"
                     }
                   }
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/endpointlevel/ethrottling",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/1",
                 "is_collection" : false,
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "qos/ratelimit/router" : {
                   "client_capacity" : 5,
                   "every" : "1m",
                   "max_rate" : 5,
                   "strategy" : "ip"
                 },
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "newClient" ],
                   "scopes_key" : "scope"
                 }
               },
               "method" : "GET",
               "timeout" : "10ns"
             }, {
               "endpoint" : "/endpointlevel/eipfilter",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/1",
                 "is_collection" : false,
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "newClient" ],
                   "scopes_key" : "scope"
                 },
                 "plugin/req-resp-modifier" : {
                   "name" : [ "ip-filter" ],
                   "ip-filter" : {
                     "CIDR" : [ "10.233.70.1" ],
                     "allow" : false
                   }
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/endpointlevel/erspmaniplationep",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects/7",
                 "is_collection" : false,
                 "encoding" : "no-op",
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "newClient" ],
                   "scopes_key" : "scope"
                 },
                 "modifier/response-body-generator" : {
                   "content_type" : "application/json",
                   "debug" : true,
                   "template" : "ewogICJBZGRyZXNzIjoge3sgdG9Kc29uIC5yZXNwX2JvZHkgfX0sCiAgInN0YXR1c19jb2RlIjoge3sgdG9Kc29uIC5yZXNwX3N0YXR1cyB9fSwKICAiaGVhZGVycyI6IHt7IHRvSnNvbiAucmVzcF9oZWFkZXJzIH19Cn0="
                 }
               },
               "output_encoding" : "no-op",
               "method" : "GET"
             }, {
               "endpoint" : "/endpointlevel/regexcontentreplacer",
               "backend" : [ {
                 "host" : [ "http://10.175.1.68:3000" ],
                 "url_pattern" : "/Testregexcontentreplacer",
                 "is_collection" : false,
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "newClient" ],
                   "scopes_key" : "scope"
                 },
                 "plugin/req-resp-modifier" : {
                   "name" : [ "content-replacer" ],
                   "content-replacer" : {
                     "data.creditcard" : {
                       "find" : "(^\\d{4})(.*)",
                       "replace" : "${1}-XXXX",
                       "regexp" : true
                     }
                   }
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/endpointlevel/ejmes",
               "backend" : [ {
                 "host" : [ "https://api.nationalize.io" ],
                 "url_pattern" : "/",
                 "is_collection" : false,
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "modifier/jmespath" : {
                   "expr" : "country[?probability > `0.03` ].country_id"
                 },
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "newClient" ],
                   "scopes_key" : "scope"
                 }
               },
               "method" : "GET",
               "input_query_strings" : [ "name" ]
             }, {
               "endpoint" : "/endpointlevel/staticrsp",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/1",
                 "is_collection" : false,
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "proxy" : {
                   "static" : {
                     "data" : {
                       "Hi" : "I am from static message"
                     },
                     "strategy" : "always"
                   }
                 },
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "newClient" ],
                   "scopes_key" : "scope"
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/backend/{id}",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects/{id}",
                 "is_collection" : true,
                 "encoding" : "no-op",
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakendtest" ],
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "no-op",
               "method" : "GET"
             }, {
               "endpoint" : "/myfirstapi/myfirstendpoint",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/1",
                 "is_collection" : false,
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "json",
               "method" : "GET"
             } ],
             "extra_config" : {
               "router" : {
                 "return_error_msg" : true
               },
               "security/cors" : {
                 "allow_origins" : [ "*" ],
                 "allow_methods" : [ "GET", "POST", "PUT", "DELETE", "PATCH" ],
                 "allow_headers" : [ "*" ],
                 "expose_headers" : [ "*" ],
                 "allow_credentials" : true
               },
               "plugin/http-server" : {
                 "name" : [ "url-rewrite" ],
                 "ip-filter" : {
                   "id" : 1,
                   "CIDR" : [ "10.175.1.70" ],
                   "allow" : false
                 }
               }
             }
           }
