apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/krakend.json",
             "version" : 3,
             "name" : "MassilGW",
             "port" : 8082,
             "host" : [ "localhost" ],
             "timeout" : "10000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "echo_endpoint" : false,
             "endpoints" : [ {
               "endpoint" : "/basictest/flatmap",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects",
                 "is_collection" : true,
                 "extra_config" : {
                   "proxy" : {
                     "flatmap_filter" : [ {
                       "type" : "move",
                       "args" : [ "collection.*.data", "collection.*.newdata" ]
                     } ]
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "method" : "GET"
             }, {
               "endpoint" : "/basictest/flatmapobject",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects/7",
                 "extra_config" : {
                   "proxy" : {
                     "flatmap_filter" : [ {
                       "type" : "move",
                       "args" : [ "data.year", "Year" ]
                     } ]
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "method" : "GET"
             }, {
               "endpoint" : "/basictest/deny",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/1",
                 "extra_config" : { },
                 "method" : "GET",
                 "deny" : [ "title", "userId", "body" ],
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "method" : "GET"
             }, {
               "endpoint" : "/basictest/jmes",
               "backend" : [ {
                 "host" : [ "https://api.nationalize.io" ],
                 "url_pattern" : "/",
                 "extra_config" : {
                   "modifier/jmespath" : {
                     "expr" : "country[?probability > `0.02` ].country_id"
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "method" : "GET",
               "input_query_strings" : [ "name" ]
             }, {
               "endpoint" : "/basictest/testrsp",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev/" ],
                 "url_pattern" : "/objects/7",
                 "extra_config" : {
                   "modifier/response-body-generator" : {
                     "template" : "ewogICJkYXRhIjoge3sgdG9Kc29uIC5yZXNwX2JvZHkgfX0sCiAgInN0YXR1c19jb2RlIjoge3sgdG9Kc29uIC5yZXNwX3N0YXR1cyB9fSwKICAiaGVhZGVycyI6IHt7IHRvSnNvbiAucmVzcF9oZWFkZXJzfX0KfQo=",
                     "content_type" : "application/json",
                     "debug" : true
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "output_encoding" : "no-op",
               "method" : "GET"
             }, {
               "endpoint" : "/basictest/target/objectname",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev/" ],
                 "url_pattern" : "/objects/7",
                 "extra_config" : { },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "method" : "GET"
             }, {
               "endpoint" : "/basictest/samplersp",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects/7",
                 "is_collection" : false,
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "modifier/response-body-generator" : {
                   "template" : "ewogICJkYXRhIjoge3sgdG9Kc29uIC5yZXNwX2JvZHkgfX0sCiAgInN0YXR1c19jb2RlIjoge3sgdG9Kc29uIC5yZXNwX3N0YXR1cyB9fSwKICAiaGVhZGVycyI6IHt7IHRvSnNvbiAucmVzcF9oZWFkZXJzIH19Cn0K",
                   "content_type" : "application/json",
                   "debug" : true
                 }
               },
               "output_encoding" : "no-op",
               "method" : "GET"
             }, {
               "endpoint" : "/billing/apple",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects/6",
                 "is_collection" : false,
                 "encoding" : "json",
                 "method" : "GET"
               } ],
               "extra_config" : { },
               "method" : "GET"
             } ],
             "extra_config" : { }
           }
