apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/krakend.json",
             "version" : 3,
             "name" : "MassilGW",
             "port" : 8082,
             "host" : [ "localhost" ],
             "timeout" : "3000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "echo_endpoint" : false,
             "endpoints" : [ {
               "endpoint" : "/basic/securityPolicies",
               "backend" : [ {
                 "host" : [ "https://api.nationalize.io" ],
                 "url_pattern" : "/",
                 "is_collection" : false,
                 "encoding" : "json",
                 "method" : "GET"
               } ],
               "extra_config" : { },
               "method" : "GET"
             }, {
               "endpoint" : "/basic/flatmap",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects/7",
                 "mapping" : {
                   "data" : "Renamedata"
                 },
                 "extra_config" : { },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               }, {
                 "host" : [ "https://api.restful-api.dev/" ],
                 "url_pattern" : "/objects/7",
                 "extra_config" : {
                   "proxy" : {
                     "flatmap_filter" : [ {
                       "type" : "move",
                       "args" : [ "data.year", "NewYear" ]
                     } ]
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "method" : "GET"
             }, {
               "endpoint" : "/basic/objects",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects",
                 "is_collection" : false,
                 "method" : "GET"
               } ],
               "extra_config" : { },
               "input_headers" : [ "" ],
               "method" : "GET",
               "input_query_strings" : [ "name" ]
             } ],
             "extra_config" : { }
           }
