apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/v2.7/krakend.json",
             "version" : 3,
             "name" : "gateway",
             "port" : 8082,
             "timeout" : "6000ms",
             "cache_ttl" : "1h",
             "debug_endpoint" : true,
             "echo_endpoint" : false,
             "plugin" : {
               "pattern" : ".so",
               "folder" : "/opt/krakend/plugins/"
             },
             "endpoints" : [ {
               "method" : "PUT",
               "output_encoding" : "json",
               "backend" : [ {
                 "method" : "PUT",
                 "url_pattern" : "/pet",
                 "host" : [ "https://petstore3.swagger.io" ],
                 "encoding" : "no-op",
                 "extra_config" : { }
               } ],
               "endpoint" : "/api/v3/pet",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               }
             }, {
               "method" : "POST",
               "output_encoding" : "json",
               "backend" : [ {
                 "method" : "POST",
                 "url_pattern" : "/pet",
                 "host" : [ "https://petstore3.swagger.io" ],
                 "encoding" : "no-op",
                 "extra_config" : { }
               } ],
               "endpoint" : "/api/v3/pet",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               }
             }, {
               "method" : "GET",
               "output_encoding" : "json",
               "backend" : [ {
                 "method" : "GET",
                 "url_pattern" : "/pet/findByStatus",
                 "host" : [ "https://petstore3.swagger.io" ],
                 "encoding" : "no-op",
                 "extra_config" : { }
               } ],
               "endpoint" : "/api/v3/pet/findByStatus",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               }
             }, {
               "method" : "GET",
               "output_encoding" : "json",
               "backend" : [ {
                 "method" : "GET",
                 "url_pattern" : "/pet/findByTags",
                 "host" : [ "https://petstore3.swagger.io" ],
                 "encoding" : "no-op",
                 "extra_config" : { }
               } ],
               "endpoint" : "/api/v3/pet/findByTags",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               }
             }, {
               "method" : "GET",
               "output_encoding" : "json",
               "backend" : [ {
                 "method" : "GET",
                 "url_pattern" : "/pet/{petId}",
                 "host" : [ "https://petstore3.swagger.io" ],
                 "encoding" : "no-op",
                 "extra_config" : { }
               } ],
               "endpoint" : "/api/v3/pet/{petId}",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               }
             }, {
               "method" : "POST",
               "output_encoding" : "json",
               "backend" : [ {
                 "method" : "POST",
                 "url_pattern" : "/pet/{petId}",
                 "host" : [ "https://petstore3.swagger.io" ],
                 "encoding" : "no-op",
                 "extra_config" : { }
               } ],
               "endpoint" : "/api/v3/pet/{petId}",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               }
             }, {
               "method" : "DELETE",
               "output_encoding" : "json",
               "backend" : [ {
                 "method" : "DELETE",
                 "url_pattern" : "/pet/{petId}",
                 "host" : [ "https://petstore3.swagger.io" ],
                 "encoding" : "no-op",
                 "extra_config" : { }
               } ],
               "endpoint" : "/api/v3/pet/{petId}",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               }
             }, {
               "method" : "POST",
               "output_encoding" : "json",
               "backend" : [ {
                 "method" : "POST",
                 "url_pattern" : "/pet/{petId}/uploadImage",
                 "host" : [ "https://petstore3.swagger.io" ],
                 "encoding" : "no-op",
                 "extra_config" : { }
               } ],
               "endpoint" : "/api/v3/pet/{petId}/uploadImage",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               }
             }, {
               "method" : "GET",
               "output_encoding" : "json",
               "backend" : [ {
                 "method" : "GET",
                 "url_pattern" : "/store/inventory",
                 "host" : [ "https://petstore3.swagger.io" ],
                 "encoding" : "no-op",
                 "extra_config" : { }
               } ],
               "endpoint" : "/api/v3/store/inventory",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               }
             }, {
               "method" : "POST",
               "output_encoding" : "json",
               "backend" : [ {
                 "method" : "POST",
                 "url_pattern" : "/store/order",
                 "host" : [ "https://petstore3.swagger.io" ],
                 "encoding" : "no-op",
                 "extra_config" : { }
               } ],
               "endpoint" : "/api/v3/store/order",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               }
             }, {
               "method" : "GET",
               "output_encoding" : "json",
               "backend" : [ {
                 "method" : "GET",
                 "url_pattern" : "/store/order/{orderId}",
                 "host" : [ "https://petstore3.swagger.io" ],
                 "encoding" : "no-op",
                 "extra_config" : { }
               } ],
               "endpoint" : "/api/v3/store/order/{orderId}",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               }
             }, {
               "method" : "DELETE",
               "output_encoding" : "json",
               "backend" : [ {
                 "method" : "DELETE",
                 "url_pattern" : "/store/order/{orderId}",
                 "host" : [ "https://petstore3.swagger.io" ],
                 "encoding" : "no-op",
                 "extra_config" : { }
               } ],
               "endpoint" : "/api/v3/store/order/{orderId}",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               }
             }, {
               "method" : "POST",
               "output_encoding" : "json",
               "backend" : [ {
                 "method" : "POST",
                 "url_pattern" : "/user",
                 "host" : [ "https://petstore3.swagger.io" ],
                 "encoding" : "no-op",
                 "extra_config" : { }
               } ],
               "endpoint" : "/api/v3/user",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               }
             }, {
               "method" : "POST",
               "output_encoding" : "json",
               "backend" : [ {
                 "method" : "POST",
                 "url_pattern" : "/user/createWithList",
                 "host" : [ "https://petstore3.swagger.io" ],
                 "encoding" : "no-op",
                 "extra_config" : { }
               } ],
               "endpoint" : "/api/v3/user/createWithList",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               }
             }, {
               "method" : "GET",
               "output_encoding" : "json",
               "backend" : [ {
                 "method" : "GET",
                 "url_pattern" : "/user/login",
                 "host" : [ "https://petstore3.swagger.io" ],
                 "encoding" : "no-op",
                 "extra_config" : { }
               } ],
               "endpoint" : "/api/v3/user/login",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               }
             }, {
               "method" : "GET",
               "output_encoding" : "json",
               "backend" : [ {
                 "method" : "GET",
                 "url_pattern" : "/user/logout",
                 "host" : [ "https://petstore3.swagger.io" ],
                 "encoding" : "no-op",
                 "extra_config" : { }
               } ],
               "endpoint" : "/api/v3/user/logout",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               }
             }, {
               "method" : "GET",
               "output_encoding" : "json",
               "backend" : [ {
                 "method" : "GET",
                 "url_pattern" : "/user/{username}",
                 "host" : [ "https://petstore3.swagger.io" ],
                 "encoding" : "no-op",
                 "extra_config" : { }
               } ],
               "endpoint" : "/api/v3/user/{username}",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               }
             }, {
               "method" : "PUT",
               "output_encoding" : "json",
               "backend" : [ {
                 "method" : "PUT",
                 "url_pattern" : "/user/{username}",
                 "host" : [ "https://petstore3.swagger.io" ],
                 "encoding" : "no-op",
                 "extra_config" : { }
               } ],
               "endpoint" : "/api/v3/user/{username}",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               }
             }, {
               "method" : "DELETE",
               "output_encoding" : "json",
               "backend" : [ {
                 "method" : "DELETE",
                 "url_pattern" : "/user/{username}",
                 "host" : [ "https://petstore3.swagger.io" ],
                 "encoding" : "no-op",
                 "extra_config" : { }
               } ],
               "endpoint" : "/api/v3/user/{username}",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               }
             }, {
               "method" : "GET",
               "backend" : [ {
                 "method" : "GET",
                 "url_pattern" : "/posts/1",
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "is_collection" : false,
                 "extra_config" : { }
               } ],
               "endpoint" : "/test123/test123ep",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "newClient" ],
                   "scopes_key" : "scope"
                 }
               }
             } ],
             "extra_config" : {
               "router" : {
                 "return_error_msg" : true
               },
               "security/cors" : {
                 "allow_origins" : [ "*" ],
                 "allow_methods" : [ "GET", "POST", "PUT", "DELETE", "PATCH" ],
                 "allow_headers" : [ "*" ],
                 "expose_headers" : [ "*" ],
                 "allow_credentials" : true
               },
               "plugin/http-server" : {
                 "name" : [ "url-rewrite" ],
                 "ip-filter" : {
                   "id" : 1,
                   "CIDR" : [ "10.175.1.70" ],
                   "allow" : false
                 }
               }
             }
           }
