apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/krakend.json",
             "version" : 3,
             "name" : "Test Gateway",
             "port" : 8080,
             "host" : [ "http://localhost.com" ],
             "timeout" : "3000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "echo_endpoint" : false,
             "endpoints" : [ {
               "endpoint" : "/test3/testing",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts",
                 "is_collection" : true,
                 "encoding" : "json",
                 "method" : "GET"
               } ],
               "extra_config" : { },
               "output_encoding" : "json",
               "method" : "GET"
             } ],
             "extra_config" : { }
           }
