apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/krakend.json",
             "version" : 3,
             "name" : "MassilGW",
             "port" : 8082,
             "host" : [ "localhost" ],
             "timeout" : "10000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "echo_endpoint" : false,
             "endpoints" : [ {
               "endpoint" : "/basicoperations/sample",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/3",
                 "extra_config" : { },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/basicoperations/testquery",
               "backend" : [ {
                 "host" : [ "https://api.nationalize.io/" ],
                 "url_pattern" : "/",
                 "is_collection" : false,
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 }
               },
               "method" : "GET",
               "input_query_strings" : [ "name" ]
             }, {
               "endpoint" : "/basicoperations/flatmap",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects",
                 "is_collection" : true,
                 "extra_config" : {
                   "proxy" : {
                     "flatmap_filter" : [ {
                       "type" : "move",
                       "args" : [ "collection.*.data", "collection.*.newdata" ]
                     } ]
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/basicoperations/flatmapobject",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects/7",
                 "extra_config" : {
                   "proxy" : {
                     "flatmap_filter" : [ {
                       "type" : "move",
                       "args" : [ "data.year", "year" ]
                     } ]
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/basicoperations/respmanipulation",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev/" ],
                 "url_pattern" : "/objects/7",
                 "extra_config" : {
                   "modifier/response-body-generator" : {
                     "template" : "ewogICJkYXRhIjoge3sgdG9Kc29uIC5yZXNwX2JvZHkgfX0sCiAgInN0YXR1c19jb2RlIjoge3sgdG9Kc29uIC5yZXNwX3N0YXR1cyB9fSwKICAiaGVhZGVycyI6IHt7IHRvSnNvbiAucmVzcF9oZWFkZXJzIH19Cn0=",
                     "content_type" : "application/json"
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 }
               },
               "output_encoding" : "no-op",
               "method" : "GET"
             }, {
               "endpoint" : "/basicoperations/endpointthrottling",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/1",
                 "is_collection" : false,
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "qos/ratelimit/router" : {
                   "max_rate" : 5,
                   "every" : "1m",
                   "strategy" : "ip"
                 },
                 "auth/basic" : {
                   "users" : {
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/basicoperations/contentreplacer",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects/7",
                 "extra_config" : {
                   "plugin/req-resp-modifier" : {
                     "name" : [ "content-replacer" ],
                     "content-replacer" : {
                       "data" : {
                         "find" : "Intel Core i9",
                         "replace" : "Intel Core i10",
                         "regexp" : false
                       }
                     }
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/basicoperations/responseschemavald",
               "backend" : [ {
                 "host" : [ "https://api.nationalize.io" ],
                 "url_pattern" : "/",
                 "extra_config" : {
                   "plugin/req-resp-modifier" : {
                     "name" : [ "response-schema-validator" ],
                     "response-schema-validator" : {
                       "schema" : {
                         "type" : "object",
                         "properties" : {
                           "count" : {
                             "type" : "string"
                           },
                           "country" : {
                             "type" : "array",
                             "items" : {
                               "type" : "object",
                               "properties" : {
                                 "country_id" : {
                                   "type" : "string"
                                 },
                                 "probability" : {
                                   "type" : "string"
                                 }
                               },
                               "required" : [ "country_id", "probability" ]
                             }
                           },
                           "name" : {
                             "type" : "string"
                           }
                         },
                         "required" : [ "count", "country", "name" ]
                       },
                       "error" : {
                         "body" : "Schema is not valid",
                         "status" : 400
                       }
                     }
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 }
               },
               "method" : "GET",
               "input_query_strings" : [ "name" ]
             }, {
               "endpoint" : "/basicoperations/merge",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/1",
                 "extra_config" : { },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               }, {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects/7",
                 "extra_config" : { },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/basicoperations/jmespath",
               "backend" : [ {
                 "host" : [ "https://api.nationalize.io/" ],
                 "url_pattern" : "/",
                 "extra_config" : {
                   "modifier/jmespath" : {
                     "expr" : "country[?probability > `0.03` ].country_id"
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 }
               },
               "method" : "GET",
               "input_query_strings" : [ "name" ]
             }, {
               "endpoint" : "/basicoperations/responsemanipulationWithGotmpl",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects/7",
                 "encoding" : "No-Op",
                 "extra_config" : {
                   "modifier/response-body-generator" : {
                     "template" : "ewogICJkYXRhIjoge3sgdG9Kc29uIC5yZXNwX2JvZHkgfX0sCiAgInN0YXR1c19jb2RlIjoge3sgdG9Kc29uIC5yZXNwX3N0YXR1cyB9fSwKICAiaGVhZGVycyI6IHt7IHRvSnNvbiAucmVzcF9oZWFkZXJzIH19Cn0=",
                     "content_type" : "application/json",
                     "debug" : true
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/basicoperations/throttling",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/1",
                 "extra_config" : {
                   "qos/ratelimit/proxy" : {
                     "max_rate" : 10,
                     "capacity" : 5,
                     "every" : "1m"
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/basicoperations/testmartian",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/1",
                 "extra_config" : {
                   "modifier/martian" : "{\n  \"body.Modifier\": {\n    \"scope\": [\n      \"response\"\n    ],\n    \"@comment\": \"Send a {'msg':'you rock!'}\",\n    \"body\": \"eyJtc2ciOiJ5b3Ugcm9jayEifQ==\",\n    \"contentType\": \"application/json\"\n  }\n}"
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 }
               },
               "method" : "GET"
             } ],
             "extra_config" : {
               "security/cors" : {
                 "allow_origins" : [ "*" ],
                 "allow_methods" : [ "GET", "HEAD", "POST" ],
                 "allow_headers" : [ "*" ],
                 "allow_credentials" : true
               }
             }
           }
