apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/v2.7/krakend.json",
             "version" : 3,
             "name" : "gateway",
             "port" : 8082,
             "timeout" : "3000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "echo_endpoint" : true,
             "plugin" : {
               "pattern" : ".so",
               "folder" : "/opt/krakend/plugins/"
             },
             "endpoints" : [ {
               "endpoint" : "/martianapi/bmartianep",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/1",
                 "extra_config" : {
                   "modifier/martian" : {
                     "body.Modifier" : {
                       "scope" : [ "response" ],
                       "@comment" : "Send a {'msg':'you rock!'}",
                       "body" : "eyJtc2ciOiJ5b3Ugcm9jayEifQ==",
                       "contentType" : "application/json"
                     }
                   }
                 },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakendtest" ],
                   "scopes_key" : "scope"
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/martianapi/martianep",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/1",
                 "is_collection" : false,
                 "extra_config" : {
                   "qos/ratelimit/proxy" : {
                     "every" : "1m",
                     "max_rate" : 5,
                     "capacity" : 5
                   },
                   "modifier/martian" : {
                     "body.Modifier" : {
                       "scope" : [ "response" ],
                       "@comment" : "Send a {'msg':'you rock!'}",
                       "body" : "eyJtc2ciOiJ5b3Ugcm9jayEifQ==",
                       "contentType" : "application/json"
                     }
                   }
                 },
                 "method" : "GET",
                 "sd" : "static"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakendtest" ],
                   "scopes_key" : "scope"
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/jmes/respmanupilation",
               "backend" : [ {
                 "host" : [ "https://api.nationalize.io" ],
                 "url_pattern" : "/",
                 "extra_config" : {
                   "modifier/jmespath" : {
                     "expr" : "country[?probability > `0.03` ].country_id"
                   }
                 },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakendtest" ],
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "json",
               "method" : "GET",
               "input_query_strings" : [ "name" ]
             }, {
               "endpoint" : "/resttosoapapi/resttosoapep",
               "backend" : [ {
                 "host" : [ "http://www.dneonline.com" ],
                 "url_pattern" : "/calculator.asmx",
                 "is_collection" : false,
                 "encoding" : "xml",
                 "extra_config" : { },
                 "method" : "POST",
                 "sd" : "static"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakendtest" ],
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "xml",
               "method" : "POST"
             } ],
             "extra_config" : {
               "router" : {
                 "return_error_msg" : true
               },
               "security/cors" : {
                 "allow_origins" : [ "*" ],
                 "allow_methods" : [ "GET", "HEAD", "POST" ],
                 "allow_headers" : [ "*" ],
                 "expose_headers" : [ "*" ],
                 "allow_credentials" : true
               }
             }
           }
