apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/krakend.json",
             "version" : 3,
             "name" : "MassilGW",
             "port" : 8082,
             "host" : [ "null" ],
             "timeout" : "3000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "echo_endpoint" : false,
             "plugin" : {
               "pattern" : ".so",
               "folder" : "/opt/krakend/plugins/"
             },
             "endpoints" : [ {
               "endpoint" : "/backend/backendrespmanipulation",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com/" ],
                 "url_pattern" : "/posts",
                 "is_collection" : true,
                 "extra_config" : {
                   "proxy" : { }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               }, {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects",
                 "is_collection" : true,
                 "encoding" : "json",
                 "extra_config" : {
                   "proxy" : { }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "output_encoding" : "json",
               "method" : "GET"
             }, {
               "endpoint" : "/backend/respschema",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts",
                 "is_collection" : true,
                 "encoding" : "json",
                 "extra_config" : {
                   "plugin/req-resp-modifier" : {
                     "name" : [ "response-schema-validator" ],
                     "response-schema-validator" : {
                       "error" : {
                         "body" : "Validation Error yyy",
                         "status" : 422
                       },
                       "schema" : {
                         "type" : "array",
                         "items" : {
                           "type" : "object",
                           "properties" : {
                             "body" : {
                               "type" : "string"
                             },
                             "id" : {
                               "type" : "number"
                             },
                             "title" : {
                               "type" : "string"
                             },
                             "userId" : {
                               "type" : "number"
                             }
                           },
                           "required" : [ "body", "id", "title", "userId" ]
                         }
                       }
                     }
                   },
                   "proxy" : { }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "output_encoding" : "json-collection",
               "method" : "GET"
             }, {
               "endpoint" : "/mucontext/getBrew",
               "backend" : [ {
                 "host" : [ "https://api.openbrewerydb.org" ],
                 "url_pattern" : "/breweries",
                 "is_collection" : true,
                 "encoding" : "json",
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "modifier/jmespath" : {
                   "expr" : "collection[?city == 'Bend'].name"
                 },
                 "proxy" : {
                   "static" : {
                     "data" : {
                       "status" : 200,
                       "message" : "success"
                     },
                     "strategy" : "always"
                   }
                 }
               },
               "output_encoding" : "json",
               "method" : "GET"
             } ],
             "extra_config" : {
               "router" : {
                 "return_error_msg" : true,
                 "disable_gzip" : true
               }
             },
             "client_tls" : {
               "id" : 102
             },
             "idle_timeout" : "0s",
             "max_idle_connections" : 0,
             "max_idle_connections_per_host" : 250,
             "read_header_timeout" : "0s",
             "read_timeout" : "0s",
             "write_timeout" : "0s"
           }
