apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/v2.7/krakend.json",
             "version" : 3,
             "name" : "gateway",
             "port" : 8082,
             "timeout" : "6000ms",
             "cache_ttl" : "1h",
             "debug_endpoint" : false,
             "echo_endpoint" : true,
             "plugin" : {
               "pattern" : ".so",
               "folder" : "/opt/krakend/plugins/"
             },
             "endpoints" : [ {
               "method" : "GET",
               "backend" : [ {
                 "method" : "GET",
                 "url_pattern" : "/posts/{id}",
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "is_collection" : false,
                 "extra_config" : { }
               } ],
               "endpoint" : "/endpointlevel/erequestpolicy/{id}",
               "extra_config" : {
                 "security/policies" : {
                   "req" : {
                     "policies" : [ "req_params.Id.matches('^[0-9]+$')" ],
                     "error" : {
                       "body" : "{\"Message\":\"Please provide integer values only\"}",
                       "status" : 400,
                       "content_type" : "application/json"
                     }
                   }
                 }
               }
             }, {
               "method" : "GET",
               "backend" : [ {
                 "method" : "GET",
                 "url_pattern" : "/posts/1",
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "is_collection" : false,
                 "extra_config" : { }
               } ],
               "endpoint" : "/endpointlevel/eipfilter",
               "extra_config" : {
                 "plugin/req-resp-modifier" : {
                   "name" : [ "ip-filter" ],
                   "ip-filter" : {
                     "CIDR" : [ "10.233.70.1" ],
                     "allow" : false
                   }
                 }
               }
             }, {
               "method" : "GET",
               "backend" : [ {
                 "method" : "GET",
                 "url_pattern" : "/posts/1",
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "is_collection" : false,
                 "extra_config" : { }
               } ],
               "endpoint" : "/endpointlevel/ethrottling",
               "extra_config" : {
                 "qos/ratelimit/router" : {
                   "client_capacity" : 5,
                   "every" : "1m",
                   "max_rate" : 5,
                   "strategy" : "ip"
                 }
               },
               "timeout" : "10ns"
             }, {
               "method" : "POST",
               "backend" : [ {
                 "method" : "GET",
                 "url_pattern" : "/objects/7",
                 "host" : [ "https://api.restful-api.dev" ],
                 "is_collection" : false,
                 "extra_config" : { }
               } ],
               "endpoint" : "/endpointlevel/ereqschemavald",
               "extra_config" : {
                 "validation/json-schema" : {
                   "$schema" : "http://json-schema.org/draft-07/schema#",
                   "type" : "object",
                   "properties" : {
                     "id" : {
                       "type" : "string"
                     },
                     "name" : {
                       "type" : "string"
                     },
                     "data" : {
                       "type" : "object",
                       "properties" : {
                         "year" : {
                           "type" : "integer"
                         },
                         "price" : {
                           "type" : "number"
                         },
                         "CPU model" : {
                           "type" : "string"
                         },
                         "Hard disk size" : {
                           "type" : "string"
                         }
                       },
                       "required" : [ "year", "price", "CPU model", "Hard disk size" ]
                     }
                   },
                   "required" : [ "id", "name", "data" ]
                 }
               }
             }, {
               "method" : "GET",
               "backend" : [ {
                 "method" : "GET",
                 "url_pattern" : "/objects/{id}",
                 "host" : [ "https://api.restful-api.dev/" ],
                 "is_collection" : false,
                 "extra_config" : { }
               } ],
               "endpoint" : "/endpointlevel/responseschemavald/{id}",
               "extra_config" : {
                 "plugin/req-resp-modifier" : {
                   "name" : [ "response-schema-validator" ],
                   "response-schema-validator" : {
                     "error" : {
                       "body" : "Inavlid response jsonschema not valid",
                       "status" : 400
                     },
                     "schema" : {
                       "$schema" : "http://json-schema.org/draft-07/schema#",
                       "type" : "object",
                       "properties" : {
                         "id" : {
                           "type" : "string"
                         },
                         "name" : {
                           "type" : "string"
                         },
                         "data" : {
                           "type" : "object",
                           "properties" : {
                             "year" : {
                               "type" : "integer"
                             },
                             "price" : {
                               "type" : "number"
                             },
                             "CPU model" : {
                               "type" : "string"
                             },
                             "Hard disk size" : {
                               "type" : "string"
                             }
                           },
                           "required" : [ "year", "price", "CPU model", "Hard disk size" ]
                         }
                       },
                       "required" : [ "id", "name", "data" ]
                     }
                   }
                 }
               }
             }, {
               "method" : "GET",
               "backend" : [ {
                 "method" : "GET",
                 "url_pattern" : "/posts/1",
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "is_collection" : false,
                 "extra_config" : { }
               } ],
               "endpoint" : "/endpointlevel/eresppolicy",
               "extra_config" : { }
             }, {
               "method" : "GET",
               "backend" : [ {
                 "method" : "GET",
                 "url_pattern" : "/posts/1",
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "is_collection" : false,
                 "extra_config" : { }
               } ],
               "endpoint" : "/endpointlevel/invalidrsppolicy",
               "extra_config" : {
                 "security/policies" : {
                   "resp" : {
                     "error" : {
                       "body" : "{\"Message\":\"Test feild is not present in response\"}",
                       "status" : 400,
                       "content_type" : "application/json"
                     },
                     "policies" : [ "!isEmpty(resp_data.test)" ]
                   }
                 }
               }
             }, {
               "method" : "GET",
               "backend" : [ {
                 "method" : "GET",
                 "url_pattern" : "/posts/1",
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "is_collection" : false,
                 "extra_config" : { }
               } ],
               "endpoint" : "/endpointlevel/staticrsp",
               "extra_config" : {
                 "proxy" : {
                   "static" : {
                     "data" : {
                       "Hi" : "I am from static message"
                     },
                     "strategy" : "always"
                   }
                 }
               }
             }, {
               "method" : "POST",
               "output_encoding" : "xml",
               "backend" : [ {
                 "method" : "POST",
                 "url_pattern" : "/calculator.asmx",
                 "host" : [ "http://www.dneonline.com" ],
                 "is_collection" : false,
                 "encoding" : "xml",
                 "extra_config" : {
                   "backend/soap" : {
                     "debug" : true,
                     "template" : "PHNvYXA6RW52ZWxvcGUgeG1sbnM6c29hcD0iaHR0cDovL3d3dy53My5vcmcvMjAwMy8wNS9zb2FwLWVudmVsb3BlIiB4bWxuczp0ZW09Imh0dHA6Ly90ZW1wdXJpLm9yZy8iPgogICA8c29hcDpIZWFkZXIvPgogICA8c29hcDpCb2R5PgogICAgICA8dGVtOkFkZD4KICAgICAgICAgPHRlbTppbnRBPnt7IC5yZXFfYm9keS5BIH19PC90ZW06aW50QT4KICAgICAgICAgPHRlbTppbnRCPnt7IC5yZXFfYm9keS5CIH19PC90ZW06aW50Qj4KICAgICAgPC90ZW06QWRkPgogICA8L3NvYXA6Qm9keT4KPC9zb2FwOkVudmVsb3BlPg==",
                     "content_type" : "text/xml"
                   }
                 },
                 "sd" : "static"
               } ],
               "endpoint" : "/endpointlevel/resttosoap",
               "extra_config" : { }
             }, {
               "method" : "GET",
               "backend" : [ {
                 "method" : "GET",
                 "url_pattern" : "/Testregexcontentreplacer",
                 "host" : [ "http://10.175.1.68:3000" ],
                 "is_collection" : false,
                 "extra_config" : { }
               } ],
               "endpoint" : "/endpointlevel/regexcontentreplacer",
               "extra_config" : {
                 "plugin/req-resp-modifier" : {
                   "name" : [ "content-replacer" ],
                   "content-replacer" : {
                     "data.creditcard" : {
                       "find" : "(^\\d{4})(.*)",
                       "replace" : "${1}-XXXX",
                       "regexp" : true
                     }
                   }
                 }
               }
             }, {
               "method" : "GET",
               "backend" : [ {
                 "method" : "GET",
                 "url_pattern" : "/",
                 "host" : [ "https://api.nationalize.io" ],
                 "is_collection" : false,
                 "extra_config" : { }
               } ],
               "endpoint" : "/endpointlevel/ejmes",
               "extra_config" : {
                 "modifier/jmespath" : {
                   "expr" : "country[?probability > `0.03` ].country_id"
                 }
               },
               "input_query_strings" : [ "name" ]
             }, {
               "method" : "GET",
               "backend" : [ {
                 "method" : "GET",
                 "url_pattern" : "/posts/1",
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "is_collection" : false,
                 "extra_config" : { }
               } ],
               "endpoint" : "/endpointlevel/validjwtpolicy",
               "extra_config" : { }
             }, {
               "method" : "GET",
               "output_encoding" : "no-op",
               "backend" : [ {
                 "method" : "GET",
                 "url_pattern" : "/objects/7",
                 "host" : [ "https://api.restful-api.dev" ],
                 "is_collection" : false,
                 "encoding" : "no-op",
                 "extra_config" : { }
               } ],
               "endpoint" : "/endpointlevel/erspmaniplationep",
               "extra_config" : {
                 "modifier/response-body-generator" : {
                   "content_type" : "application/json",
                   "debug" : true,
                   "template" : "ewogICJBZGRyZXNzIjoge3sgdG9Kc29uIC5yZXNwX2JvZHkgfX0sCiAgInN0YXR1c19jb2RlIjoge3sgdG9Kc29uIC5yZXNwX3N0YXR1cyB9fSwKICAiaGVhZGVycyI6IHt7IHRvSnNvbiAucmVzcF9oZWFkZXJzIH19Cn0="
                 }
               }
             } ],
             "extra_config" : {
               "router" : {
                 "return_error_msg" : true
               },
               "security/cors" : {
                 "allow_origins" : [ "*" ],
                 "allow_methods" : [ "GET", "POST", "PUT", "DELETE", "PATCH" ],
                 "allow_headers" : [ "*" ],
                 "expose_headers" : [ "*" ],
                 "allow_credentials" : true
               },
               "plugin/http-server" : {
                 "name" : [ "url-rewrite" ],
                 "ip-filter" : {
                   "id" : 1,
                   "CIDR" : [ "10.175.1.70" ],
                   "allow" : false
                 }
               },
               "telemetry/logging" : {
                 "format" : "default",
                 "syslog_facility" : "local3",
                 "level" : "DEBUG",
                 "prefix" : "[KRAKEND]",
                 "syslog" : false,
                 "stdout" : true
               },
               "telemetry/logstash" : {
                 "enabled" : true
               }
             }
           }
