apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/krakend.json",
             "version" : 3,
             "name" : "MassilGW",
             "port" : 8082,
             "host" : [ "null" ],
             "timeout" : "3000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "echo_endpoint" : false,
             "plugin" : {
               "pattern" : ".so",
               "folder" : "/opt/krakend/plugins/"
             },
             "endpoints" : [ {
               "endpoint" : "/mucontext/getBrew",
               "backend" : [ {
                 "host" : [ "https://api.openbrewerydb.org" ],
                 "url_pattern" : "/breweries",
                 "is_collection" : true,
                 "encoding" : "json",
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "modifier/jmespath" : {
                   "expr" : "collection[?city == 'Bend'].name"
                 },
                 "proxy" : {
                   "static" : {
                     "data" : {
                       "status" : 200,
                       "message" : "success"
                     },
                     "strategy" : "always"
                   }
                 }
               },
               "output_encoding" : "json",
               "method" : "GET"
             } ],
             "extra_config" : {
               "router" : {
                 "return_error_msg" : true,
                 "disable_gzip" : true
               }
             },
             "client_tls" : {
               "id" : 102
             },
             "idle_timeout" : "0s",
             "max_idle_connections" : 0,
             "max_idle_connections_per_host" : 250,
             "read_header_timeout" : "0s",
             "read_timeout" : "0s",
             "write_timeout" : "0s"
           }
