apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/v2.7/krakend.json",
             "version" : 3,
             "name" : "gateway",
             "port" : 8082,
             "timeout" : "3000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "echo_endpoint" : true,
             "plugin" : {
               "pattern" : ".so",
               "folder" : "/opt/krakend/plugins/"
             },
             "endpoints" : [ {
               "endpoint" : "/sampleResponseschema/responseschemavald/{id}",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects/{id}",
                 "is_collection" : false,
                 "extra_config" : {
                   "plugin/req-resp-modifier" : {
                     "name" : [ "response-schema-validator" ],
                     "response-schema-validator" : {
                       "error" : {
                         "body" : "Inavlid response jsonschema not valid",
                         "status" : 400
                       },
                       "schema" : {
                         "type" : "object",
                         "properties" : {
                           "id" : {
                             "type" : "string"
                           },
                           "name" : {
                             "type" : "string"
                           },
                           "data" : {
                             "type" : "object",
                             "properties" : {
                               "year" : {
                                 "type" : "integer"
                               },
                               "price" : {
                                 "type" : "number"
                               },
                               "CPU model" : {
                                 "type" : "string"
                               },
                               "Hard disk size" : {
                                 "type" : "string"
                               }
                             },
                             "required" : [ "year", "price", "CPU model", "Hard disk size" ]
                           }
                         },
                         "required" : [ "id", "name", "data" ]
                       }
                     }
                   }
                 },
                 "method" : "GET",
                 "sd" : "static"
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "sampleconsumer" : "$2a$10$UxHb5GLfNLIEPNeL7dMV.OfareBLIQggkSHFZyA3dtlQDayy4kviK"
                   }
                 }
               },
               "method" : "GET"
             } ],
             "extra_config" : {
               "router" : {
                 "return_error_msg" : true
               },
               "security/cors" : {
                 "allow_origins" : [ "*" ],
                 "allow_methods" : [ "GET", "HEAD", "POST" ],
                 "allow_headers" : [ "*" ],
                 "expose_headers" : [ "*" ],
                 "allow_credentials" : true
               },
               "telemetry/logging" : {
                 "format" : "default",
                 "syslog_facility" : "local3",
                 "level" : "DEBUG",
                 "prefix" : "MASSIL",
                 "stdout" : true
               },
               "telemetry/logstash" : {
                 "enabled" : true
               }
             }
           }
