apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/krakend.json",
             "version" : 3,
             "name" : "MassilGW",
             "port" : 8082,
             "host" : [ "null" ],
             "timeout" : "3000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "plugin" : {
               "pattern" : ".so",
               "folder" : "/opt/krakend/plugins/"
             },
             "endpoints" : [ {
               "endpoint" : "/keynull",
               "output_encoding" : "json",
               "method" : "GET"
             }, {
               "endpoint" : "/keynull",
               "output_encoding" : "json",
               "method" : "GET"
             }, {
               "endpoint" : "/keynull",
               "output_encoding" : "json",
               "method" : "GET"
             }, {
               "endpoint" : "/keynull",
               "output_encoding" : "json",
               "method" : "GET"
             }, {
               "endpoint" : "/keynull",
               "output_encoding" : "json",
               "method" : "GET"
             }, {
               "endpoint" : "/key/stopticket",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects/8",
                 "encoding" : "json",
                 "extra_config" : {
                   "proxy" : {
                     "flatmap_filter" : [ {
                       "type" : "move",
                       "args" : [ "collection.*.data", "collection.*.newdata" ]
                     }, {
                       "type" : "move",
                       "args" : [ "collection.*.data", "collection.*.newdata" ]
                     } ]
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 }
               },
               "output_encoding" : "json-collection",
               "method" : "GET"
             }, {
               "endpoint" : "/key/backendrespmanipulation",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects",
                 "is_collection" : true,
                 "encoding" : "json",
                 "extra_config" : {
                   "modifier/jmespath" : {
                     "expr" : "collection[].{id: id, name: name}"
                   },
                   "proxy" : { }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 }
               },
               "output_encoding" : "json",
               "method" : "GET"
             }, {
               "endpoint" : "/key/rootobject",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev/" ],
                 "url_pattern" : "/objects/7",
                 "extra_config" : {
                   "proxy" : { }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 }
               },
               "method" : "GET"
             } ],
             "extra_config" : {
               "router" : {
                 "id" : 102,
                 "disable_gzip" : true
               }
             },
             "client_tls" : {
               "id" : 102
             },
             "idle_timeout" : "0s",
             "max_idle_connections" : 0,
             "max_idle_connections_per_host" : 250,
             "read_header_timeout" : "0s",
             "read_timeout" : "0s",
             "write_timeout" : "0s"
           }
