apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/krakend.json",
             "version" : 3,
             "name" : "gateway",
             "port" : 8082,
             "timeout" : "3000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "echo_endpoint" : false,
             "plugin" : {
               "pattern" : ".so",
               "folder" : "/opt/krakend/plugins/"
             },
             "endpoints" : [ {
               "endpoint" : "/basicoperation/testqueryparam",
               "backend" : [ {
                 "host" : [ "https://api.nationalize.io" ],
                 "url_pattern" : "/",
                 "is_collection" : false,
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "HarryPotter" ],
                   "scopes_key" : "scope"
                 }
               },
               "method" : "GET",
               "input_query_strings" : [ "name" ]
             }, {
               "endpoint" : "/basicoperation/testcollection",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts",
                 "is_collection" : true,
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "HarryPotter" ],
                   "scopes_key" : "scope"
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/basicoperation/testendpoint",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/1",
                 "is_collection" : false,
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "HarryPotter" ],
                   "scopes_key" : "scope"
                 }
               },
               "method" : "GET"
             } ],
             "extra_config" : {
               "security/cors" : {
                 "allow_origins" : [ "*" ],
                 "allow_methods" : [ "GET", "HEAD", "POST" ],
                 "allow_headers" : [ "*" ],
                 "expose_headers" : [ "*" ],
                 "allow_credentials" : true
               }
             }
           }
