apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/krakend.json",
             "version" : 3,
             "name" : "gateway",
             "port" : 8082,
             "timeout" : "3000ms",
             "cache_ttl" : "300s",
             "plugin" : {
               "pattern" : ".so",
               "folder" : "/opt/krakend/plugins/"
             },
             "endpoints" : [ {
               "endpoint" : "/api1/keycloak-protected",
               "backend" : [ {
                 "host" : [ "http://localhost:8083" ],
                 "url_pattern" : "/__health"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://localhost:8080/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://localhost:8080/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/api2/keycloak-protected1",
               "backend" : [ {
                 "host" : [ "http://localhost:8082" ],
                 "url_pattern" : "/__health"
               } ],
               "extra_config" : {
                 "auth/api-keys" : {
                   "roles" : [ "consumer_ramesh" ]
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/demo/keycloak-protected2",
               "backend" : [ {
                 "host" : [ "http://localhost:8082" ],
                 "url_pattern" : "/__health"
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "consumer_ramesh" : "$2a$10$zptiG1eswxpKw9.OHVKjx.qKyShcbuGSWGetaMIRQ/vazBIgiiOP2",
                     "consumer_neel" : "$2a$10$eHerowcCmAhwo0sRgvtp.uDVmRzqUvT3Hkr9v5aZRmkMMUgat.6j."
                   }
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/demo/keycloak-protected1",
               "backend" : [ {
                 "host" : [ "http://localhost:8082" ],
                 "url_pattern" : "/__health"
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "consumer_ramesh" : "$2a$10$zptiG1eswxpKw9.OHVKjx.qKyShcbuGSWGetaMIRQ/vazBIgiiOP2",
                     "consumer_neel" : "$2a$10$eHerowcCmAhwo0sRgvtp.uDVmRzqUvT3Hkr9v5aZRmkMMUgat.6j."
                   }
                 }
               },
               "method" : "GET"
             } ],
             "extra_config" : { }
           }
