apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/krakend.json",
             "version" : 3,
             "name" : "apigateway",
             "port" : 8082,
             "timeout" : "3000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "echo_endpoint" : false,
             "plugin" : {
               "pattern" : ".so",
               "folder" : "/opt/krakend/plugins/"
             },
             "endpoints" : [ {
               "endpoint" : "/api1/keycloak-protected",
               "backend" : [ {
                 "host" : [ "http://localhost:8082" ],
                 "url_pattern" : "/__health",
                 "extra_config" : { }
               }, {
                 "host" : [ "test.com" ],
                 "url_pattern" : "/gettttl",
                 "mapping" : {
                   "hello" : 333
                 },
                 "group" : "dds",
                 "is_collection" : false,
                 "encoding" : "json",
                 "extra_config" : {
                   "qos/http-cache" : {
                     "shared" : false
                   },
                   "plugin/req-resp-modifier" : {
                     "name" : [ "content-replacer" ],
                     "response-schema-validator" : {
                       "error" : {
                         "body" : {
                           "error" : "error is here"
                         },
                         "status" : 0
                       },
                       "schema" : {
                         "hi" : 238947294
                       }
                     },
                     "content-replacer" : {
                       "Hii" : 222
                     }
                   },
                   "modifier/jmespath" : {
                     "@comment" : "sdss",
                     "expr" : "LL"
                   },
                   "modifier/response-body-generator" : {
                     "content_type" : "application/json",
                     "debug" : false,
                     "template" : "skjnlndjakdncnksnklk"
                   },
                   "proxy" : {
                     "flatmap_filter" : [ {
                       "type" : "sddfs",
                       "args" : [ "sdkf.skkf;;;w;w" ]
                     } ]
                   },
                   "security/policies" : {
                     "auto_join_policies" : true,
                     "debug" : true,
                     "disable_macros" : true,
                     "jwt" : {
                       "policies" : [ "wdd" ]
                     },
                     "resp" : {
                       "error" : {
                         "body" : "{\"Hi\":999}",
                         "status" : 0,
                         "content_type" : "string"
                       },
                       "policies" : [ "string" ]
                     }
                   }
                 },
                 "target" : "aj",
                 "method" : "GET",
                 "disable_host_sanitize" : false,
                 "sd" : "static"
               } ],
               "extra_config" : {
                 "modifier/jmespath" : {
                   "@comment" : "string",
                   "expr" : "string"
                 },
                 "proxy" : {
                   "static" : {
                     "data" : { },
                     "strategy" : "string"
                   }
                 },
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://localhost:8080/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://localhost:8080/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 },
                 "plugin/req-resp-modifier" : {
                   "name" : [ "content-replacer" ],
                   "content-replacer" : { }
                 },
                 "modifier/response-body-generator" : {
                   "content_type" : "string",
                   "debug" : true,
                   "template" : "string"
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/api2/api/keycloak-protected22",
               "backend" : [ {
                 "host" : [ "http://localhost:8082" ],
                 "url_pattern" : "/__health",
                 "extra_config" : { }
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://localhost:8080/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://localhost:8080/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/api2/keycloak-protected22",
               "backend" : [ {
                 "host" : [ "http://localhost:8082" ],
                 "url_pattern" : "/__health",
                 "extra_config" : { }
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://localhost:8080/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://localhost:8080/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               },
               "method" : "GET"
             } ],
             "extra_config" : { }
           }
