apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/krakend.json",
             "version" : 3,
             "name" : "MassilGW",
             "port" : 8082,
             "host" : [ "localhost" ],
             "timeout" : "3000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "echo_endpoint" : false,
             "endpoints" : [ {
               "endpoint" : "/test/testEP",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/1",
                 "extra_config" : {
                   "qos/ratelimit/proxy" : {
                     "max_rate" : 10,
                     "capacity" : 10,
                     "every" : "1m"
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : {
                 "qos/ratelimit/router" : {
                   "max_rate" : 5,
                   "capacity" : 5,
                   "every" : "1m",
                   "strategy" : "ip"
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/test/testsoapep",
               "backend" : [ {
                 "host" : [ "http://www.dneonline.com" ],
                 "url_pattern" : "/calculator.asmx",
                 "extra_config" : { },
                 "method" : "POST",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "output_encoding" : "no-op",
               "input_headers" : [ "Content-Type" ],
               "method" : "POST"
             }, {
               "endpoint" : "/ep/ep",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/1",
                 "is_collection" : false,
                 "encoding" : "json",
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.60:8080/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.60:8080/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "MassilTechId" ],
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "json",
               "method" : "GET"
             } ],
             "extra_config" : {
               "security/cors" : {
                 "allow_origins" : [ "*" ],
                 "allow_methods" : [ "GET", "POST" ],
                 "allow_headers" : [ "*" ],
                 "allow_credentials" : true
               }
             }
           }
