apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/krakend.json",
             "version" : 3,
             "name" : "gateway",
             "port" : 8082,
             "timeout" : "3000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : true,
             "echo_endpoint" : true,
             "plugin" : {
               "pattern" : ".so",
               "folder" : "/opt/krakend/plugins/"
             },
             "endpoints" : [ {
               "endpoint" : "/basicmanipulations/firstendpoint",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/1",
                 "is_collection" : false,
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "Testconsumerid" ],
                   "scopes_key" : "scope"
                 },
                 "plugin/req-resp-modifier" : {
                   "name" : [ "content-replacer" ],
                   "content-replacer" : {
                     "fggfh" : {
                       "find" : "gfhgf",
                       "replace" : "gfhg",
                       "regexp" : true
                     }
                   }
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/v4/operation/respschemaval",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects/3",
                 "is_collection" : false,
                 "encoding" : "json",
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakend" ],
                   "scopes_key" : "scope"
                 },
                 "plugin/req-resp-modifier" : {
                   "name" : [ "response-schema-validator" ],
                   "response-schema-validator" : {
                     "error" : {
                       "body" : "Validation Error",
                       "status" : 422
                     },
                     "schema" : {
                       "type" : "object",
                       "properties" : {
                         "data" : {
                           "type" : "object",
                           "properties" : {
                             "capacity GB" : {
                               "type" : "string"
                             },
                             "color" : {
                               "type" : "string"
                             }
                           },
                           "required" : [ "capacity GB", "color" ]
                         }
                       }
                     }
                   }
                 }
               },
               "output_encoding" : "json",
               "method" : "GET"
             }, {
               "endpoint" : "/v4/operation/ratelimit",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects/4",
                 "is_collection" : false,
                 "encoding" : "json",
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "qos/ratelimit/router" : {
                   "every" : "30s",
                   "max_rate" : 3,
                   "strategy" : "ip"
                 },
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakend" ],
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "json",
               "method" : "GET"
             }, {
               "endpoint" : "/v4/operation/bcontentreplacer",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects/6",
                 "encoding" : "json",
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakend" ],
                   "scopes_key" : "scope"
                 },
                 "plugin/req-resp-modifier" : {
                   "name" : [ "content-replacer" ],
                   "content-replacer" : {
                     "120" : {
                       "find" : "120",
                       "replace" : "300",
                       "regexp" : false
                     }
                   }
                 }
               },
               "output_encoding" : "json",
               "method" : "GET"
             }, {
               "endpoint" : "/v4/operation/ipwhitelist",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects/5",
                 "is_collection" : false,
                 "encoding" : "json",
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakend" ],
                   "scopes_key" : "scope"
                 },
                 "plugin/req-resp-modifier" : {
                   "name" : [ "ip-filter" ],
                   "ip-filter" : {
                     "CIDR" : [ "10.233.70.0" ],
                     "allow" : true
                   }
                 }
               },
               "output_encoding" : "json",
               "method" : "GET"
             }, {
               "endpoint" : "/v4/operation/bjmesresp",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects",
                 "is_collection" : true,
                 "encoding" : "json",
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "modifier/jmespath" : {
                   "expr" : "collection[].{id: id}"
                 },
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakend" ],
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "json",
               "method" : "GET"
             } ],
             "extra_config" : {
               "security/cors" : {
                 "allow_origins" : [ "*" ],
                 "allow_methods" : [ "GET", "HEAD", "POST" ],
                 "allow_headers" : [ "*" ],
                 "expose_headers" : [ "*" ],
                 "allow_credentials" : true
               }
             }
           }
