apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/v2.7/krakend.json",
             "version" : 3,
             "name" : "gateway",
             "port" : 8082,
             "timeout" : "6000ms",
             "cache_ttl" : "1h",
             "debug_endpoint" : true,
             "echo_endpoint" : false,
             "plugin" : {
               "pattern" : ".so",
               "folder" : "/opt/krakend/plugins/"
             },
             "endpoints" : [ {
               "method" : "GET",
               "output_encoding" : "json",
               "backend" : [ {
                 "method" : "GET",
                 "url_pattern" : "hn",
                 "host" : [ "local" ],
                 "is_collection" : false,
                 "encoding" : "json",
                 "extra_config" : { }
               } ],
               "endpoint" : "/testing/efc",
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               }
             } ],
             "extra_config" : {
               "router" : {
                 "return_error_msg" : true
               },
               "security/cors" : {
                 "allow_origins" : [ "*" ],
                 "allow_methods" : [ "GET", "POST", "PUT", "DELETE", "PATCH" ],
                 "allow_headers" : [ "*" ],
                 "expose_headers" : [ "*" ],
                 "allow_credentials" : true
               },
               "plugin/http-server" : {
                 "name" : [ "url-rewrite" ],
                 "ip-filter" : {
                   "id" : 1,
                   "CIDR" : [ "10.175.1.70" ],
                   "allow" : false
                 }
               }
             }
           }
