apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/krakend.json",
             "version" : 3,
             "name" : "MassilGW",
             "port" : 8082,
             "host" : [ "null" ],
             "timeout" : "3000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "echo_endpoint" : false,
             "plugin" : {
               "pattern" : ".so",
               "folder" : "/opt/krakend/plugins/"
             },
             "endpoints" : [ {
               "endpoint" : "/backend/eregex",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects",
                 "is_collection" : true,
                 "encoding" : "json",
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "vijay" : "$2a$10$3P8gTibWNOZ05FgRCU5R8em8er2LXQnmk2tnUFlEMG95tGio6uPtO",
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 },
                 "plugin/req-resp-modifier" : {
                   "name" : [ "content-replacer" ],
                   "content-replacer" : {
                     "hem" : {
                       "find" : "data",
                       "replace" : "enrollData",
                       "regexp" : true
                     }
                   }
                 }
               },
               "output_encoding" : "json-collection",
               "method" : "GET"
             }, {
               "endpoint" : "/backend/backendrespmanipulation",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com/" ],
                 "url_pattern" : "/posts",
                 "is_collection" : true,
                 "extra_config" : {
                   "proxy" : { }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               }, {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects",
                 "is_collection" : true,
                 "encoding" : "json",
                 "extra_config" : {
                   "proxy" : { }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "vijay" : "$2a$10$3P8gTibWNOZ05FgRCU5R8em8er2LXQnmk2tnUFlEMG95tGio6uPtO",
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 }
               },
               "output_encoding" : "json",
               "method" : "GET"
             }, {
               "endpoint" : "/backend/bmartain",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects",
                 "encoding" : "json",
                 "extra_config" : {
                   "modifier/martian" : {
                     "body.Modifier" : {
                       "scope" : [ "request", "response" ],
                       "@comment" : "Send a {'Status':'Success'}",
                       "body" : "eydTdGF0dXMnOidTdWNjZXNzJ30=",
                       "contentType" : "application/json"
                     }
                   },
                   "proxy" : { }
                 },
                 "method" : "POST",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "vijay" : "$2a$10$3P8gTibWNOZ05FgRCU5R8em8er2LXQnmk2tnUFlEMG95tGio6uPtO",
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 }
               },
               "output_encoding" : "json",
               "method" : "POST"
             }, {
               "endpoint" : "/backend/ejmesresp",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects",
                 "is_collection" : true,
                 "encoding" : "json",
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "modifier/jmespath" : {
                   "expr" : "collection[].{id: id, name: name}"
                 },
                 "auth/basic" : {
                   "users" : {
                     "vijay" : "$2a$10$3P8gTibWNOZ05FgRCU5R8em8er2LXQnmk2tnUFlEMG95tGio6uPtO",
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 }
               },
               "output_encoding" : "json",
               "method" : "GET"
             }, {
               "endpoint" : "/backend/ereqSchemaVal",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects",
                 "encoding" : "json",
                 "extra_config" : {
                   "proxy" : { }
                 },
                 "method" : "POST",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "vijay" : "$2a$10$3P8gTibWNOZ05FgRCU5R8em8er2LXQnmk2tnUFlEMG95tGio6uPtO",
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 },
                 "validation/json-schema" : {
                   "type" : "object",
                   "properties" : {
                     "id" : {
                       "type" : "string"
                     },
                     "name" : {
                       "type" : "string"
                     },
                     "data" : {
                       "type" : "object",
                       "properties" : {
                         "year" : {
                           "type" : "integer"
                         },
                         "price" : {
                           "type" : "number"
                         },
                         "CPU model" : {
                           "type" : "string"
                         },
                         "Hard disk size" : {
                           "type" : "string"
                         }
                       },
                       "required" : [ "year", "price", "CPU model", "Hard disk size" ]
                     }
                   },
                   "required" : [ "name" ]
                 }
               },
               "output_encoding" : "json",
               "method" : "POST"
             }, {
               "endpoint" : "/backend/eipfilter",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects",
                 "is_collection" : true,
                 "encoding" : "json",
                 "extra_config" : {
                   "proxy" : { }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "vijay" : "$2a$10$3P8gTibWNOZ05FgRCU5R8em8er2LXQnmk2tnUFlEMG95tGio6uPtO",
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 },
                 "plugin/req-resp-modifier" : {
                   "name" : [ "ip-filter" ],
                   "ip-filter" : {
                     "CIDR" : [ "10.233.70.0" ],
                     "allow" : true
                   }
                 }
               },
               "output_encoding" : "json-collection",
               "method" : "GET"
             }, {
               "endpoint" : "/backend/respschema",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts",
                 "is_collection" : true,
                 "encoding" : "json",
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "vijay" : "$2a$10$3P8gTibWNOZ05FgRCU5R8em8er2LXQnmk2tnUFlEMG95tGio6uPtO",
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 }
               },
               "output_encoding" : "json-collection",
               "method" : "GET",
               "cache_ttl" : "60s",
               "timeout" : "40s"
             }, {
               "endpoint" : "/backend/eratelimit",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects",
                 "is_collection" : true,
                 "encoding" : "json",
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "qos/ratelimit/router" : {
                   "every" : "20s",
                   "max_rate" : 2,
                   "strategy" : "ip"
                 },
                 "auth/basic" : {
                   "users" : {
                     "vijay" : "$2a$10$3P8gTibWNOZ05FgRCU5R8em8er2LXQnmk2tnUFlEMG95tGio6uPtO",
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 }
               },
               "output_encoding" : "json",
               "method" : "GET"
             }, {
               "endpoint" : "/backend/erespSchemaVal",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects",
                 "encoding" : "json",
                 "extra_config" : {
                   "proxy" : { }
                 },
                 "method" : "POST",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "vijay" : "$2a$10$3P8gTibWNOZ05FgRCU5R8em8er2LXQnmk2tnUFlEMG95tGio6uPtO",
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 },
                 "plugin/req-resp-modifier" : {
                   "name" : [ "response-schema-validator" ],
                   "response-schema-validator" : {
                     "error" : {
                       "body" : "\\x56616c69646174696f6e204572726f72",
                       "status" : 422
                     },
                     "schema" : {
                       "type" : "object",
                       "properties" : {
                         "id" : {
                           "type" : "string"
                         },
                         "name" : {
                           "type" : "string"
                         },
                         "createdAt" : {
                           "type" : "string"
                         },
                         "data" : {
                           "type" : "object",
                           "properties" : {
                             "year" : {
                               "type" : "integer"
                             },
                             "price" : {
                               "type" : "number"
                             },
                             "CPU model" : {
                               "type" : "string"
                             },
                             "Hard disk size" : {
                               "type" : "string"
                             }
                           },
                           "required" : [ "year", "price", "CPU model", "Hard disk size" ]
                         }
                       },
                       "required" : [ "name", "id", "createdAt" ]
                     }
                   }
                 }
               },
               "output_encoding" : "json",
               "method" : "POST"
             }, {
               "endpoint" : "/backend/eparams",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects",
                 "is_collection" : true,
                 "encoding" : "json",
                 "extra_config" : {
                   "proxy" : { }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "vijay" : "$2a$10$3P8gTibWNOZ05FgRCU5R8em8er2LXQnmk2tnUFlEMG95tGio6uPtO",
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 }
               },
               "output_encoding" : "json",
               "method" : "GET"
             }, {
               "endpoint" : "/backend/bcontreplacer",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects",
                 "is_collection" : false,
                 "encoding" : "json",
                 "method" : "POST"
               } ],
               "extra_config" : {
                 "auth/basic" : {
                   "users" : {
                     "vijay" : "$2a$10$3P8gTibWNOZ05FgRCU5R8em8er2LXQnmk2tnUFlEMG95tGio6uPtO",
                     "consumer1" : "$2a$10$2qHOavVO4mXzh2XNLPziQuC7H1M/pjPlrFmnADyWEI7i5YqGW.4Uq"
                   }
                 }
               },
               "output_encoding" : "json",
               "method" : "POST"
             } ],
             "extra_config" : {
               "router" : {
                 "return_error_msg" : true,
                 "disable_gzip" : true
               },
               "security/cors" : {
                 "allow_origins" : [ "*" ],
                 "allow_methods" : [ "GET", "POST" ],
                 "allow_headers" : [ "*" ],
                 "allow_credentials" : true
               }
             },
             "client_tls" : {
               "id" : 102
             },
             "idle_timeout" : "0s",
             "max_idle_connections" : 0,
             "max_idle_connections_per_host" : 250,
             "read_header_timeout" : "0s",
             "read_timeout" : "0s",
             "write_timeout" : "0s"
           }
