apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/krakend.json",
             "version" : 3,
             "name" : "gateway",
             "port" : 8082,
             "timeout" : "3000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : true,
             "echo_endpoint" : true,
             "plugin" : {
               "pattern" : ".so",
               "folder" : "/opt/krakend/plugins/"
             },
             "endpoints" : [ {
               "endpoint" : "/requestManipulation/requestmanipulationep",
               "backend" : [ {
                 "host" : [ "https://reqres.in" ],
                 "url_pattern" : "/api/users",
                 "is_collection" : false,
                 "extra_config" : {
                   "modifier/body-generator" : {
                     "content_type" : "application/json",
                     "debug" : true,
                     "template" : "ewogICAgIm5hbWUiOiAie3sgLnJlcV9ib2R5LnVwZGF0ZS5kYXRhLm5hbWUgfX0iLAogICAgImVtYWlsIjogInt7IC5yZXFfYm9keS51cGRhdGUuZGF0YS5lbWFpbCB9fSIKfQ=="
                   }
                 },
                 "method" : "POST",
                 "sd" : "static"
               } ],
               "extra_config" : {
                 "auth/api-keys" : {
                   "roles" : [ "Developer" ]
                 }
               },
               "method" : "POST"
             }, {
               "endpoint" : "/testsoap/testsoapep",
               "backend" : [ {
                 "host" : [ "http://www.dneonline.com" ],
                 "url_pattern" : "/calculator.asmx",
                 "is_collection" : false,
                 "encoding" : "xml",
                 "extra_config" : {
                   "backend/soap" : {
                     "debug" : true,
                     "template" : "PHNvYXA6RW52ZWxvcGUgeG1sbnM6c29hcD0iaHR0cDovL3d3dy53My5vcmcvMjAwMy8wNS9zb2FwLWVudmVsb3BlIiB4bWxuczp0ZW09Imh0dHA6Ly90ZW1wdXJpLm9yZy8iPgogICA8c29hcDpIZWFkZXIvPgogICA8c29hcDpCb2R5PgogICAgICA8dGVtOkFkZD4KICAgICAgICAgPHRlbTppbnRBPnt7IC5yZXFfYm9keS5BIH19PC90ZW06aW50QT4KICAgICAgICAgPHRlbTppbnRCPnt7IC5yZXFfYm9keS5CIH19PC90ZW06aW50Qj4KICAgICAgPC90ZW06QWRkPgogICA8L3NvYXA6Qm9keT4KPC9zb2FwOkVudmVsb3BlPg==",
                     "content_type" : "text/xml"
                   }
                 },
                 "method" : "POST"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "xml",
               "method" : "POST"
             }, {
               "endpoint" : "/resttosoapapi/resttosoap",
               "backend" : [ {
                 "host" : [ "http://www.dneonline.com" ],
                 "url_pattern" : "/calculator.asmx",
                 "is_collection" : false,
                 "encoding" : "xml",
                 "extra_config" : {
                   "backend/soap" : {
                     "debug" : true,
                     "template" : "PHNvYXA6RW52ZWxvcGUgeG1sbnM6c29hcD0iaHR0cDovL3d3dy53My5vcmcvMjAwMy8wNS9zb2FwLWVudmVsb3BlIiB4bWxuczp0ZW09Imh0dHA6Ly90ZW1wdXJpLm9yZy8iPgogICA8c29hcDpIZWFkZXIvPgogICA8c29hcDpCb2R5PgogICAgICA8dGVtOkFkZD4KICAgICAgICAgPHRlbTppbnRBPnt7IC5yZXFfYm9keS5BIH19PC90ZW06aW50QT4KICAgICAgICAgPHRlbTppbnRCPnt7IC5yZXFfYm9keS5CIH19PC90ZW06aW50Qj4KICAgICAgPC90ZW06QWRkPgogICA8L3NvYXA6Qm9keT4KPC9zb2FwOkVudmVsb3BlPg==",
                     "content_type" : "text/xml"
                   }
                 },
                 "method" : "POST",
                 "sd" : "static"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "Testconsumerid" ],
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "xml",
               "method" : "POST"
             }, {
               "endpoint" : "/resttosoapi/restosoaap",
               "backend" : [ {
                 "host" : [ "http://www.dneonline.com" ],
                 "url_pattern" : "/calculator.asmx",
                 "is_collection" : false,
                 "encoding" : "xml",
                 "extra_config" : { },
                 "method" : "POST"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "Testconsumerid" ],
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "xml",
               "method" : "POST"
             }, {
               "endpoint" : "/testdelete/testep1",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/1",
                 "is_collection" : false,
                 "extra_config" : { },
                 "method" : "POST"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes_key" : "scope"
                 }
               },
               "method" : "POST"
             }, {
               "endpoint" : "/gatewayratelimitapi/gratelimitep",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/1",
                 "is_collection" : false,
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "Testconsumerid" ],
                   "scopes_key" : "scope"
                 }
               },
               "method" : "GET"
             } ],
             "extra_config" : {
               "security/cors" : {
                 "allow_origins" : [ "*" ],
                 "allow_methods" : [ "GET", "HEAD", "POST" ],
                 "allow_headers" : [ "*" ],
                 "expose_headers" : [ "*" ],
                 "allow_credentials" : true
               },
               "auth/api-keys" : {
                 "identifier" : "Authorization",
                 "strategy" : "header",
                 "keys" : [ {
                   "key" : "272dc167-2072-400c-b1ea-3474157ca469",
                   "roles" : [ "Developer" ]
                 } ]
               },
               "qos/ratelimit/service" : {
                 "capacity" : 1,
                 "client_capacity" : 1,
                 "client_max_rate" : 15,
                 "every" : "1m",
                 "max_rate" : 10,
                 "strategy" : "ip"
               }
             }
           }
