apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/v2.7/krakend.json",
             "version" : 3,
             "name" : "gateway",
             "port" : 8082,
             "timeout" : "3000ms",
             "cache_ttl" : "1h",
             "debug_endpoint" : false,
             "echo_endpoint" : true,
             "plugin" : {
               "pattern" : ".so",
               "folder" : "/opt/krakend/plugins/"
             },
             "endpoints" : [ {
               "endpoint" : "/gateway/gateway/hello/{id}",
               "backend" : [ {
                 "host" : [ "http://10.175.1.58:3000" ],
                 "url_pattern" : "/gateway/hello/{id}",
                 "is_collection" : false,
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakendtest" ],
                   "scopes_key" : "scope"
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/gateway/wilcard/*",
               "backend" : [ {
                 "host" : [ "http://10.175.1.58:8290" ],
                 "url_pattern" : "/HelloWorld",
                 "is_collection" : false,
                 "extra_config" : { },
                 "method" : "GET",
                 "sd" : "static"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakendtest" ],
                   "scopes_key" : "scope"
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/gateway/hello/123",
               "backend" : [ {
                 "host" : [ "http://10.175.1.58:3000" ],
                 "url_pattern" : "/gateway/hello/123",
                 "is_collection" : false,
                 "extra_config" : { },
                 "method" : "GET",
                 "sd" : "static"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakendtest" ],
                   "scopes_key" : "scope"
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/krakend/object",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects",
                 "is_collection" : false,
                 "encoding" : "json",
                 "extra_config" : { },
                 "method" : "POST"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakendtest", "Massil@123" ],
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "json",
               "method" : "POST"
             }, {
               "endpoint" : "/krakend/object/{id}",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects/{id}",
                 "is_collection" : false,
                 "encoding" : "json",
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakendtest", "Massil@123" ],
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "json",
               "method" : "GET"
             }, {
               "endpoint" : "/krakend/objects",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects",
                 "is_collection" : true,
                 "encoding" : "json",
                 "extra_config" : { },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakendtest", "Massil@123" ],
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "json-collection",
               "method" : "GET"
             }, {
               "endpoint" : "/krakend/deleteObject/{id}",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects/{id}",
                 "is_collection" : false,
                 "encoding" : "json",
                 "extra_config" : { },
                 "method" : "DELETE"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakendtest", "Massil@123" ],
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "json",
               "method" : "DELETE"
             }, {
               "endpoint" : "/krakend/putobject/{id}",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects/{id}",
                 "is_collection" : false,
                 "encoding" : "json",
                 "extra_config" : { },
                 "method" : "PUT"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "krakendtest", "Massil@123" ],
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "json",
               "method" : "PUT"
             } ],
             "extra_config" : {
               "router" : {
                 "return_error_msg" : true
               },
               "security/cors" : {
                 "allow_origins" : [ "*" ],
                 "allow_methods" : [ "GET", "HEAD", "POST" ],
                 "allow_headers" : [ "*" ],
                 "expose_headers" : [ "*" ],
                 "allow_credentials" : true
               },
               "plugin/http-server" : {
                 "name" : [ "url-rewrite" ],
                 "url-rewrite" : {
                   "regexp" : [ [ "/hi-there/([\\w\\d\\s]+)/bar", "/gateway/hello/${1}" ] ]
                 }
               },
               "auth/validator" : {
                 "shared_cache_duration" : 3600
               }
             }
           }
