apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/v2.7/krakend.json",
             "version" : 3,
             "name" : "gateway",
             "port" : 8082,
             "timeout" : "3000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "echo_endpoint" : true,
             "plugin" : {
               "pattern" : ".so",
               "folder" : "/opt/krakend/plugins/"
             },
             "endpoints" : [ {
               "endpoint" : "/rspmanipulationapi/rspmaniplationep",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects/7",
                 "extra_config" : {
                   "modifier/response-body-generator" : {
                     "content_type" : "application/json",
                     "debug" : true,
                     "template" : "ewogICJkYXRhIjoge3sgdG9Kc29uIC5yZXNwX2JvZHkgfX0sCiAgInN0YXR1c19jb2RlIjoge3sgdG9Kc29uIC5yZXNwX3N0YXR1cyB9fSwKICAiaGVhZGVycyI6IHt7IHRvSnNvbiAucmVzcF9oZWFkZXJzIH19Cn0="
                   }
                 },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "sampleid" ],
                   "scopes_key" : "scope"
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/respmanipulationapi/respmanipulationep",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev/" ],
                 "url_pattern" : "/objects/7",
                 "encoding" : "no-op",
                 "extra_config" : {
                   "modifier/response-body-generator" : {
                     "content_type" : "application/json",
                     "debug" : true,
                     "template" : "ewogICJBZGRyZXNzIjoge3sgdG9Kc29uIC5yZXNwX2JvZHkgfX0sCiAgInN0YXR1c19jb2RlIjoge3sgdG9Kc29uIC5yZXNwX3N0YXR1cyB9fSwKICAiaGVhZGVycyI6IHt7IHRvSnNvbiAucmVzcF9oZWFkZXJzIH19Cn0="
                   }
                 },
                 "method" : "GET",
                 "sd" : "static"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "Testconsumerid", "sampleid" ],
                   "scopes_key" : "scope"
                 }
               },
               "method" : "GET"
             }, {
               "endpoint" : "/massil/massilep",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev/" ],
                 "url_pattern" : "/objects/7",
                 "extra_config" : {
                   "modifier/response-body-generator" : {
                     "content_type" : "application/json",
                     "debug" : true,
                     "template" : "ewogICAgIkFkZHJlc3MiOiB7eyB0b0pzb24gLnJlc3BfYm9keSB9fSwKICAgICJzdGF0dXNfY29kZSI6IHt7IHRvSnNvbiAucmVzcF9zdGF0dXMgfX0sCiAgICAiaGVhZGVycyI6IHt7IHRvSnNvbiAucmVzcF9oZWFkZXJzIH19Cn0="
                   }
                 },
                 "method" : "GET"
               } ],
               "extra_config" : {
                 "auth/validator" : {
                   "alg" : "RS256",
                   "jwk_url" : "http://10.175.1.110:31438/realms/master/protocol/openid-connect/certs",
                   "issuer" : "http://10.175.1.110:31438/realms/master",
                   "disable_jwk_security" : true,
                   "scopes_matcher" : "any",
                   "scopes" : [ "sampleid" ],
                   "scopes_key" : "scope"
                 }
               },
               "output_encoding" : "json",
               "method" : "GET"
             } ],
             "extra_config" : {
               "router" : {
                 "return_error_msg" : true
               },
               "security/cors" : {
                 "allow_origins" : [ "*" ],
                 "allow_methods" : [ "GET", "HEAD", "POST" ],
                 "allow_headers" : [ "*" ],
                 "expose_headers" : [ "*" ],
                 "allow_credentials" : true
               },
               "telemetry/logging" : {
                 "format" : "default",
                 "syslog_facility" : "local3",
                 "level" : "DEBUG",
                 "prefix" : "MASSIL",
                 "stdout" : true
               },
               "telemetry/logstash" : {
                 "enabled" : true
               }
             }
           }
