apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakendDemo
  namespace: krakendDemo-namespace
  labels:
    app: krakendDemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: krakendDemo
  template:
    metadata:
      annotations:
        configmap.reloader.stakater.com/reload: "krakend-config"
      labels:
        app: krakendDemo
    spec:
      containers:
      - name: krakend-container
        image: krakend/krakend-ee:2
        ports:
        - containerPort: 8082
        args:
        - run
        - -c
        - /etc/krakend/config/krakend.json
        env:
        - name: KRAKEND_LICENSE_PATH
          value: /etc/krakend/LICENSE
        volumeMounts:
        - name: krakend-config
          mountPath: /etc/krakend/config
          subPath: krakend.json
        - name: krakend-license
          mountPath: /etc/krakend/LICENSE
          subPath: LICENSE
      volumes:
      - name: krakend-config
        configMap:
          name: krakend-config
      - name: krakend-license
        secret:
          secretName: krakend-license
