apiVersion: v1
kind: Service
metadata:
  name: krakenddemo-service
  namespace: krakenddemo-namespace
spec:
  selector:
    app: krakendDemo
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
    nodePort: 31321
  type: NodePort
